const String terms="Last updated: 2023-03-27\n\n"
    "1. Introduction\n\n"
    "Welcome to Jibika Intelligic Ltd. (“Company”, “we”, “our”, “us”)!\n\n"
    "These Terms of Service (“Terms”, “Terms of Service”) govern your use of our website located at jibikaplexus.com (together or individually “Service”) operated by Jibika Intelligic Ltd..\n\n"
    "Our Privacy Policy also governs your use of our Service and explains how we collect, safeguard and disclose information that results from your use of our web pages.\n\n"
    "Your agreement with us includes these Terms and our Privacy Policy (“Agreements”). You acknowledge that you have read and understood Agreements, and agree to be bound of them.\n\n"
    "If you do not agree with (or cannot comply with) Agreements, then you may not use the Service, but please let us know by emailing at jibikaplexus@gmail.com so we can try to find a solution. These Terms apply to all visitors, users and others who wish to access or use Service.\n\n"
    "2. Communications\n\n"
    "By using our Service, you agree to subscribe to newsletters, marketing or promotional materials and other information we may send. However, you may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at jibikaplexus@gmail.com.\n\n"
    "3. Purchases\n\n"
    "If you wish to purchase any product or service made available through Service (“Purchase”), you may be asked to supply certain information relevant to your Purchase including but not limited to, your credit or debit card number, the expiration date of your card, your billing address, and your shipping information.\n\n"
    "You represent and warrant that: (i) you have the legal right to use any card(s) or other payment method(s) in connection with any Purchase; and that (ii) the information you supply to us is true, correct and complete.\n\n"
    "We may employ the use of third party services for the purpose of facilitating payment and the completion of Purchases. By submitting your information, you grant us the right to provide the information to these third parties subject to our Privacy Policy.\n\n"
    "We reserve the right to refuse or cancel your order at any time for reasons including but not limited to: product or service availability, errors in the description or price of the product or service, error in your order or other reasons.\n\n"
    "We reserve the right to refuse or cancel your order if fraud or an unauthorized or illegal transaction is suspected.\n\n"
    "4. Contests, Sweepstakes and Promotions\n\n"
    "Any contests, sweepstakes or other promotions (collectively, “Promotions”) made available through Service may be governed by rules that are separate from these Terms of Service. If you participate in any Promotions, please review the applicable rules as well as our Privacy Policy. If the rules for a Promotion conflict with these Terms of Service, Promotion rules will apply.\n\n"
    "5. Subscriptions\n\n"
    "Some parts of Service are billed on a subscription basis ('Subscription(s)'). You will be billed in advance on a recurring and periodic basis ('Billing Cycle'). Billing cycles will be set depending on the type of subscription plan you select when purchasing a Subscription.\n\n"
    "At the end of each Billing Cycle, your Subscription will automatically renew under the exact same conditions unless you cancel it or Jibika Intelligic Ltd. cancels it. You may cancel your Subscription renewal either through your online account management page or by contacting jibikaplexus@gmail.com customer support team.\n\n"
    "A valid payment method is required to process the payment for your subscription. You shall provide Jibika Intelligic Ltd. with accurate and complete billing information that may include but not limited to full name, address, state, postal or zip code, telephone number, and a valid payment method information. By submitting such payment information, you automatically authorize Jibika Intelligic Ltd. to charge all Subscription fees incurred through your account to any such payment instruments.\n\n"
    "Should automatic billing fail to occur for any reason, Jibika Intelligic Ltd. reserves the right to terminate your access to the Service with immediate effect.\n\n"
    "6. Free Trial\n\n"
    "Jibika Intelligic Ltd. may, at its sole discretion, offer a Subscription with a free trial for a limited period of time ('Free Trial').\n\n"
    "You may be required to enter your billing information in order to sign up for Free Trial.\n\n"
    "If you do enter your billing information when signing up for Free Trial, you will not be charged by Jibika Intelligic Ltd. until Free Trial has expired. On the last day of Free Trial period, unless you cancelled your Subscription, you will be automatically charged the applicable Subscription fees for the type of Subscription you have selected.\n\n"
    "At any time and without notice, Jibika Intelligic Ltd. reserves the right to (i) modify Terms of Service of Free Trial offer, or (ii) cancel such Free Trial offer.\n\n"
    "7. Fee Changes\n\n"
    "Jibika Intelligic Ltd., in its sole discretion and at any time, may modify Subscription fees for the Subscriptions. Any Subscription fee change will become effective at the end of the then-current Billing Cycle.\n\n"
    "Jibika Intelligic Ltd. will provide you with a reasonable prior notice of any change in Subscription fees to give you an opportunity to terminate your Subscription before such change becomes effective.\n\n"
    "Your continued use of Service after Subscription fee change comes into effect constitutes your agreement to pay the modified Subscription fee amount.\n\n"
    "8. Refunds\n\n"
    "We issue refunds for Contracts within 0 days of the original purchase of the Contract.\n\n"
    "9. Content\n\n"
    "Our Service allows you to post, link, store, share and otherwise make available certain information, text, graphics, videos, or other material (“Content”). You are responsible for Content that you post on or through Service, including its legality, reliability, and appropriateness.By posting Content on or through Service, You represent and warrant that: (i) Content is yours (you own it) and/or you have the right to use it and the right to grant us the rights and license as provided in these Terms, and (ii) that the posting of your Content\n\n"
    "on or through Service does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity. We reserve the right to terminate the account of anyone found to be infringing on a copyright.\n\n"
    "You retain any and all of your rights to any Content you submit, post or display on or through Service and you are responsible for protecting those rights. We take no responsibility and assume no liability for Content you or any third party posts on or through Service. However, by posting Content using Service you grant us the right and license to use, modify, publicly perform, publicly display, reproduce, and distribute such Content on and through Service. You agree that this license includes the right for us to make your Content available to other users of Service, who may also use your Content subject to these Terms.\n\n"
    "Jibika Intelligic Ltd. has the right but not the obligation to monitor and edit all Content provided by users.\n\n"
    "In addition, Content found on or through this Service are the property of Jibika Intelligic Ltd. or used with permission. You may not distribute, modify, transmit, reuse, download, repost, copy, or use said Content, whether in whole or in part, for commercial purposes or for personal gain, without express advance written permission from us.\n\n"
    "10. Prohibited Uses\n\n"
    "You may use Service only for lawful purposes and in accordance with Terms. You agree not to use Service:\n\n"
    "0.1. In any way that violates any applicable national or international law or regulation.\n\n"
    "0.2. For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content or otherwise.\n\n"
    "0.3. To transmit, or procure the sending of, any advertising or promotional material, including any “junk mail”, “chain letter,” “spam,” or any other similar solicitation.\n\n"
    "0.4. To impersonate or attempt to impersonate Company, a Company employee, another user, or any other person or entity.\n\n"
    "0.5. In any way that infringes upon the rights of others, or in any way is illegal, threatening, fraudulent, or harmful, or in connection with any unlawful, illegal, fraudulent, or harmful purpose or activity.\n\n"
    "0.6. To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of Service, or which, as determined by us, may harm or offend Company or users of Service or expose them to liability.\n\n"
    "Additionally, you agree not to:\n\n"
    "0.1. Use Service in any manner that could disable, overburden, damage, or impair Service or interfere with any other party’s use of Service, including their ability to engage in real time activities through Service.\n\n"
    "0.2. Use any robot, spider, or other automatic device, process, or means to access Service for any purpose, including monitoring or copying any of the material on Service.\n\n"
    "0.3. Use any manual process to monitor or copy any of the material on Service or for any other unauthorized purpose without our prior written consent.\n\n"
    "0.4. Use any device, software, or routine that interferes with the proper working of Service.\n\n"
    "0.5. Introduce any viruses, trojan horses, worms, logic bombs, or other material which is malicious or technologically harmful.\n\n"
    "0.6. Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of Service, the server on which Service is stored, or any server, computer, or database connected to Service.\n\n"
    "0.7. Attack Service via a denial-of-service attack or a distributed denial-of-service attack.\n\n"
    "0.8. Take any action that may damage or falsify Company rating.\n\n"
    "0.9. Otherwise attempt to interfere with the proper working of Service.\n\n"
    "11. Analytics\n\n"
    "We may use third-party Service Providers to monitor and analyze the use of our Service.\n\n"
    "12. No Use By Minors\n\n"
    "Service is intended only for access and use by individuals at least eighteen (18) years old. By accessing or using Service, you warrant and represent that you are at least eighteen (18) years of age and with the full authority, right, and capacity to enter into this agreement and abide by all of the terms and conditions of Terms. If you are not at least eighteen (18) years old, you are prohibited from both the access and usage of Service.\n\n"
    "13. Accounts\n\n"
    "When you create an account with us, you guarantee that you are above the age of 18, and that the information you provide us is accurate, complete, and current at all times. Inaccurate, incomplete, or obsolete information may result in the immediate termination of your account on Service.\n\n"
    "You are responsible for maintaining the confidentiality of your account and password, including but not limited to the restriction of access to your computer and/or account. You agree to accept responsibility for any and all activities or actions that occur under your account and/or password, whether your password is with our Service or a third-party service. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.\n\n"
    "You may not use as a username the name of another person or entity or that is not lawfully available for use, a name or trademark that is subject to any rights of another person or entity other than you, without appropriate authorization. You may not use as a username any name that is offensive, vulgar or obscene.\n\n"
    "We reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in our sole discretion.\n\n"
    "14. Intellectual Property\n\n"
    "Service and its original content (excluding Content provided by users), features and functionality are and will remain the exclusive property of Jibika Intelligic Ltd. and its licensors. Service is protected by copyright, trademark, and other laws of and foreign countries. Our trademarks may not be used in connection with any product or service without the prior written consent of Jibika Intelligic Ltd..\n\n"
    "15. Copyright Policy\n\n"
    "We respect the intellectual property rights of others. It is our policy to respond to any claim that Content posted on Service infringes on the copyright or other intellectual property rights (“Infringement”) of any person or entity.\n\n"
    "If you are a copyright owner, or authorized on behalf of one, and you believe that the copyrighted work has been copied in a way that constitutes copyright infringement, please submit your claim via email to jibikaplexus@gmail.com, with the subject line: “Copyright Infringement” and include in your claim a detailed description of the alleged Infringement as detailed below, under “DMCA Notice and Procedure for Copyright Infringement Claims”\n\n"
    "You may be held accountable for damages (including costs and attorneys’ fees) for misrepresentation or bad-faith claims on the infringement of any Content found on and/or through Service on your copyright.\n\n"
    "16. DMCA Notice and Procedure for Copyright Infringement Claims\n\n"
    "You may submit a notification pursuant to the Digital Millennium Copyright Act (DMCA) by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail):\n\n"
    "0.1. an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright’s interest;\n\n"
    "0.2. a description of the copyrighted work that you claim has been infringed, including the URL (i.e., web page address) of the location where the copyrighted work exists or a copy of the copyrighted work;\n\n"
    "0.3. identification of the URL or other specific location on Service where the material that you claim is infringing is located;\n\n"
    "0.4. your address, telephone number, and email address;\n\n"
    "0.5. a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;\n\n"
    "0.6. a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.\n\n"
    "You can contact our Copyright Agent via email at jibikaplexus@gmail.com.\n\n"
    "17. Error Reporting and Feedback\n\n"
    "You may provide us either directly at jibikaplexus@gmail.com or via third party sites and tools with information and feedback concerning errors, suggestions for improvements, ideas, problems, complaints, and other matters related to our Service (“Feedback”). You acknowledge and agree that: (i) you shall not retain, acquire or assert any intellectual property right or other right, title or interest in or to the Feedback; (ii) Company may have development ideas similar to the Feedback; (iii) Feedback does not contain confidential information or proprietary information from you or any third party; and (iv) Company is not under any obligation of confidentiality with respect to the Feedback. In the event the transfer of the ownership to the Feedback is not possible due to applicable mandatory laws, you grant Company and its affiliates an exclusive, transferable, irrevocable, free-of-charge, sub-licensable, unlimited and perpetual right to use (including copy, modify, create derivative works, publish, distribute and commercialize) Feedback in any manner and for any purpose.\n\n"
    "18. Links To Other Web Sites\n\n"
    "Our Service may contain links to third party web sites or services that are not owned or controlled by Jibika Intelligic Ltd..\n\n"
    "Jibika Intelligic Ltd. has no control over, and assumes no responsibility for the content, privacy policies, or practices of any third party web sites or services. We do not warrant the offerings of any of these entities/individuals or their websites..\n\n"
    "YOU ACKNOWLEDGE AND AGREE THAT COMPANY SHALL NOT BE RESPONSIBLE OR LIABLE, DIRECTLY OR INDIRECTLY, FOR ANY DAMAGE OR LOSS CAUSED OR ALLEGED TO BE CAUSED BY OR IN CONNECTION WITH USE OF OR RELIANCE ON ANY SUCH CONTENT, GOODS OR SERVICES AVAILABLE ON OR THROUGH ANY SUCH THIRD PARTY WEB SITES OR SERVICES.\n\n"
    "WE STRONGLY ADVISE YOU TO READ THE TERMS OF SERVICE AND PRIVACY POLICIES OF ANY THIRD PARTY WEB SITES OR SERVICES THAT YOU VISIT.\n\n"
    "19. Disclaimer Of Warranty\n\n"
    "THESE SERVICES ARE PROVIDED BY COMPANY ON AN “AS IS” AND “AS AVAILABLE” BASIS. COMPANY MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THEIR SERVICES, OR THE INFORMATION, CONTENT OR MATERIALS INCLUDED THEREIN. YOU EXPRESSLY AGREE THAT YOUR USE OF THESE SERVICES, THEIR CONTENT, AND ANY SERVICES OR ITEMS OBTAINED FROM US IS AT YOUR SOLE RISK.\n\n"
    "NEITHER COMPANY NOR ANY PERSON ASSOCIATED WITH COMPANY MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF THE SERVICES. WITHOUT LIMITING THE FOREGOING, NEITHER COMPANY NOR ANYONE ASSOCIATED WITH COMPANY REPRESENTS OR WARRANTS THAT THE SERVICES, THEIR CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT THE SERVICES OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE SERVICES OR ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.\n\n"
    "COMPANY HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.\n\n"
    "THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.\n\n"
    "20. Limitation Of Liability\n\n"
    "EXCEPT AS PROHIBITED BY LAW, YOU WILL HOLD US AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS HARMLESS FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES (INCLUDING ATTORNEYS’ FEES AND ALL RELATED COSTS AND EXPENSES OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTED), WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM THIS AGREEMENT AND ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF COMPANY HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS LIABILITY FOUND ON THE PART OF COMPANY, IT WILL BE LIMITED TO THE AMOUNT PAID FOR THE PRODUCTS AND/OR SERVICES, AND UNDER NO CIRCUMSTANCES WILL THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE PRIOR LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU.\n\n"
    "21. Termination\n\n"
    "We may terminate or suspend your account and bar access to Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of Terms.\n\n"
    "If you wish to terminate your account, you may simply discontinue using Service.\n\n"
    "All provisions of Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability.\n\n"
    "22. Governing Law\n\n"
    "These Terms shall be governed and construed in accordance with the laws of Bangladesh, which governing law applies to agreement without regard to its conflict of law provisions.\n\n"
    "Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. If any provision of these Terms is held to be invalid or unenforceable by a court, the remaining provisions of these Terms will remain in effect. These Terms constitute the entire agreement between us regarding our Service and supersede and replace any prior agreements we might have had between us regarding Service.\n\n"
    "23. Changes To Service\n\n"
    "We reserve the right to withdraw or amend our Service, and any service or material we provide via Service, in our sole discretion without notice. We will not be liable if for any reason all or any part of Service is unavailable at any time or for any period. From time to time, we may restrict access to some parts of Service, or the entire Service, to users, including registered users.\n\n"
    "24. Amendments To Terms\n\n"
    "We may amend Terms at any time by posting the amended terms on this site. It is your responsibility to review these Terms periodically.\n\n"
    "Your continued use of the Platform following the posting of revised Terms means that you accept and agree to the changes. You are expected to check this page frequently so you are aware of any changes, as they are binding on you.\n\n"
    "By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use Service.\n\n"
    "25. Waiver And Severability\n\n"
    "No waiver by Company of any term or condition set forth in Terms shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Company to assert a right or provision under Terms shall not constitute a waiver of such right or provision.\n\n"
    "If any provision of Terms is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of Terms will continue in full force and effect.\n\n"
    "26. Acknowledgement\n\n"
    "BY USING SERVICE OR OTHER SERVICES PROVIDED BY US, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF SERVICE AND AGREE TO BE BOUND BY THEM.\n\n"
    "27. Contact Us\n\n"
    "Please send your feedback, comments, requests for technical support by \n"
    "email: jibikaplexus@gmail.com.";


const String termsbn="সর্বশেষ আপডেট: 2023-03-27\n\n"
    "1. পরিচিতি\n\n"
    "Jibika Intelligic Ltd. (“কোম্পানি”, “আমরা”, “আমাদের”, “আমাদের”) স্বাগতম!\n\n"
    "এই পরিষেবার শর্তাবলী 'শর্তাবলী', 'পরিষেবার শর্তাবলী) Jibikaplexus.com (একত্রে বা পৃথকভাবে 'পরিষেবা') জিবিকা ইন্টেলিজিক লিমিটেড দ্বারা পরিচালিত আমাদের ওয়েবসাইটটির ব্যবহার নিয়ন্ত্রণ করে।\n\n"
    "আমাদের গোপনীয়তা নীতি আমাদের পরিষেবার আপনার ব্যবহারকেও নিয়ন্ত্রণ করে এবং ব্যাখ্যা করে যে আমরা কীভাবে আমাদের ওয়েব পৃষ্ঠাগুলির আপনার ব্যবহারের ফলে তথ্য সংগ্রহ, সুরক্ষা এবং প্রকাশ করি।\n\n"
    "আপনার চুক্তিতে এই শর্তাবলী এবং আমাদের গোপনীয়তা নীতি ('চুক্তি') অন্তর্ভুক্ত রয়েছে। আপনি স্বীকার করেন যে আপনি চুক্তিগুলি পড়েছেন এবং বুঝেছেন এবং সেগুলির দ্বারা আবদ্ধ হতে সম্মত হন৷\n\n"
    "আপনি যদি চুক্তির সাথে একমত না হন (বা মেনে চলতে না পারেন) তবে আপনি পরিষেবাটি ব্যবহার নাও করতে পারেন, তবে অনুগ্রহ করে jibikaplexus@gmail.com এ ইমেল করে আমাদের জানান যাতে আমরা একটি সমাধান খোঁজার চেষ্টা করতে পারি। এই শর্তাবলী সমস্ত দর্শক, ব্যবহারকারী এবং অন্যদের জন্য প্রযোজ্য যারা পরিষেবা অ্যাক্সেস করতে বা ব্যবহার করতে চান৷\n\n"
    "2. যোগাযোগ\n\n"
    "আমাদের পরিষেবা ব্যবহার করে, আপনি নিউজলেটার, বিপণন বা প্রচারমূলক উপকরণ এবং আমরা পাঠাতে পারি এমন অন্যান্য তথ্যের সদস্যতা নিতে সম্মত হন। যাইহোক, আপনি আনসাবস্ক্রাইব লিঙ্ক অনুসরণ করে বা jibikaplexus@gmail.com-এ ইমেল করে আমাদের কাছ থেকে যেকোনো বা সমস্ত যোগাযোগ গ্রহণ করা থেকে অপ্ট আউট করতে পারেন।\n\n"
    "3. কেনাকাটা\n\n"
    "আপনি যদি পরিষেবার মাধ্যমে উপলব্ধ কোনও পণ্য বা পরিষেবা কিনতে চান ('ক্রয'), আপনাকে আপনার ক্রেডিট বা ডেবিট কার্ড নম্বর, আপনার কার্ডের মেয়াদ শেষ হওয়ার তারিখ সহ কিন্তু সীমাবদ্ধ নয় এমন কিছু তথ্য সরবরাহ করতে বলা হতে পারে। , আপনার বিলিং ঠিকানা, এবং আপনার শিপিং তথ্য।\n\n"
    "আপনি প্রতিনিধিত্ব করেন এবং ওয়ারেন্টি দেন যে: (i) আপনার কাছে যেকোনো ক্রয়ের ক্ষেত্রে কোনো কার্ড(গুলি) বা অন্য অর্থপ্রদানের পদ্ধতি (গুলি) ব্যবহার করার আইনি অধিকার আছে; এবং (ii) আপনি আমাদেরকে যে তথ্য সরবরাহ করেছেন তা সঠিক, সঠিক এবং সম্পূর্ণ।\n\n"
    "আমরা অর্থপ্রদান এবং কেনাকাটা সম্পূর্ণ করার সুবিধার্থে তৃতীয় পক্ষের পরিষেবা ব্যবহার করতে পারি। আপনার তথ্য জমা দিয়ে, আপনি আমাদের গোপনীয়তা নীতি সাপেক্ষে এই তৃতীয় পক্ষকে তথ্য প্রদান করার অধিকার প্রদান করেন।\n\n"
    "পণ্য বা পরিষেবার প্রাপ্যতা, পণ্য বা পরিষেবার বিবরণ বা মূল্যে ত্রুটি, আপনার অর্ডারে ত্রুটি, বা অন্যান্য কারণ সহ কিন্তু সীমাবদ্ধ নয় এমন কারণগুলির জন্য আমরা যেকোনো সময় আপনার অর্ডার প্রত্যাখ্যান বা বাতিল করার অধিকার সংরক্ষণ করি।\n\n"
    "প্রতারণা বা অননুমোদিত বা অবৈধ লেনদেন সন্দেহ হলে আমরা আপনার অর্ডার প্রত্যাখ্যান বা বাতিল করার অধিকার সংরক্ষণ করি।\n\n"
    "4. প্রতিযোগিতা, সুইপস্টেক এবং প্রচার\n\n"
    "পরিষেবার মাধ্যমে উপলব্ধ যে কোনও প্রতিযোগিতা, সুইপস্টেক বা অন্যান্য প্রচার (সম্মিলিতভাবে, ' প্রচার') এই পরিষেবার শর্তাবলী থেকে পৃথক নিয়ম দ্বারা পরিচালিত হতে পারে। আপনি যদি কোনো প্রচারে অংশগ্রহণ করেন, অনুগ্রহ করে প্রযোজ্য নিয়মের পাশাপাশি আমাদের গোপনীয়তা নীতি পর্যালোচনা করুন। যদি এই পরিষেবার শর্তাবলীর সাথে কোনও প্রচারের নিয়মগুলি সাংঘর্ষিক হয় তবে প্রচারের নিয়মগুলি প্রযোজ্য হবে৷\n\n"
    "5. সদস্যতা\n\n"
    "পরিষেবার কিছু অংশ সাবস্ক্রিপশনের ভিত্তিতে বিল করা হয় ('সাবস্ক্রিপশন(গুলি)')৷ আপনাকে পুনরাবৃত্ত এবং পর্যায়ক্রমিক ভিত্তিতে (' বিলিং চক্র') অগ্রিম বিল করা হবে। সাবস্ক্রিপশন কেনার সময় আপনি যে ধরনের সাবস্ক্রিপশন প্ল্যান নির্বাচন করেন তার উপর নির্ভর করে বিলিং চক্র সেট করা হবে।\n\n"
    "প্রতিটি বিলিং চক্রের শেষে, আপনার সাবস্ক্রিপশন স্বয়ংক্রিয়ভাবে ঠিক একই শর্তে পুনর্নবীকরণ হবে যদি না আপনি এটি বাতিল করেন বা Jibika Intelligic Ltd. বাতিল না করেন। আপনি আপনার অনলাইন অ্যাকাউন্ট পরিচালনা পৃষ্ঠার মাধ্যমে বা jibikaplexus@gmail.com গ্রাহক সহায়তা দলের সাথে যোগাযোগ করে আপনার সদস্যতা পুনর্নবীকরণ বাতিল করতে পারেন।\n\n"
    "আপনার সদস্যতার জন্য অর্থপ্রদান প্রক্রিয়া করার জন্য একটি বৈধ অর্থপ্রদানের পদ্ধতি প্রয়োজন৷ আপনি Jibika Intelligic Ltd. কে সঠিক এবং সম্পূর্ণ বিলিং তথ্য প্রদান করবেন যাতে পুরো নাম, ঠিকানা, রাজ্য, পোস্টাল বা জিপ কোড, টেলিফোন নম্বর এবং বৈধ অর্থপ্রদানের পদ্ধতির তথ্য অন্তর্ভুক্ত থাকতে পারে তবে সীমাবদ্ধ নয়। এই ধরনের অর্থপ্রদানের তথ্য জমা দেওয়ার মাধ্যমে, আপনি স্বয়ংক্রিয়ভাবে জিবিকা ইন্টেলিজিক লিমিটেড-কে আপনার অ্যাকাউন্টের মাধ্যমে সমস্ত সাবস্ক্রিপশন ফি চার্জ করার জন্য এই জাতীয় অর্থপ্রদানের উপকরণগুলিতে অনুমোদিত করেন।\n\n"
    "কোনো কারণে স্বয়ংক্রিয় বিলিং ঘটতে ব্যর্থ হলে, Jibika Intelligic Ltd. অবিলম্বে পরিষেবাতে আপনার অ্যাক্সেস বন্ধ করার অধিকার সংরক্ষণ করে।\n\n"
    "6. বিনামূল্যে ট্রায়াল\n\n"
    "Jibika Intelligic Ltd. তার নিজস্ব বিবেচনার ভিত্তিতে, একটি সীমিত সময়ের জন্য একটি বিনামূল্যে ট্রায়াল সহ একটি সাবস্ক্রিপশন অফার করতে পারে ('ফ্রি ট্রায়াল')।\n\n"
    "একটি বিনামূল্যে ট্রায়ালের জন্য সাইন আপ করার জন্য আপনাকে আপনার বিলিং তথ্য লিখতে হতে পারে৷\n\n"
    "বিনামূল্যে ট্রায়ালের জন্য সাইন আপ করার সময় আপনি যদি আপনার বিলিং তথ্য প্রবেশ করেন, তাহলে বিনামূল্যে ট্রায়ালের মেয়াদ শেষ না হওয়া পর্যন্ত Jibika Intelligic Ltd. দ্বারা আপনাকে চার্জ করা হবে না। বিনামূল্যে ট্রায়াল সময়ের শেষ দিনে, আপনি যদি আপনার সদস্যতা বাতিল না করেন, আপনি যে ধরনের সাবস্ক্রিপশন নির্বাচন করেছেন তার জন্য আপনাকে স্বয়ংক্রিয়ভাবে প্রযোজ্য সাবস্ক্রিপশন ফি চার্জ করা হবে।\n\n"
    "যেকোন সময় এবং বিজ্ঞপ্তি ছাড়াই, Jibika Intelligic Ltd. (i) বিনামূল্যের ট্রায়াল অফারের পরিষেবার শর্তাবলী পরিবর্তন করার, অথবা (ii) এই ধরনের বিনামূল্যের ট্রায়াল অফার বাতিল করার অধিকার সংরক্ষণ করে৷\n\n"
    "7. ফি পরিবর্তন\n\n"
    "Jibika Intelligic Ltd., তার নিজস্ব বিবেচনার ভিত্তিতে এবং যেকোনো সময়ে, সাবস্ক্রিপশনের জন্য সাবস্ক্রিপশন ফি পরিবর্তন করতে পারে। যেকোনো সাবস্ক্রিপশন ফি পরিবর্তন তৎকালীন বর্তমান বিলিং চক্রের শেষে কার্যকর হবে।\n\n"
    "Jibika Intelligic Ltd. আপনাকে সাবস্ক্রিপশন ফিতে যেকোনো পরিবর্তনের যুক্তিসঙ্গত পূর্ব নোটিশ প্রদান করবে যাতে এই ধরনের পরিবর্তন কার্যকর হওয়ার আগে আপনাকে আপনার সাবস্ক্রিপশন বন্ধ করার সুযোগ দেয়।\n\n"
    "সাবস্ক্রিপশন ফি পরিবর্তন কার্যকর হওয়ার পরে আপনার পরিষেবার ক্রমাগত ব্যবহার পরিবর্তিত সাবস্ক্রিপশন ফি পরিমাণ প্রদানের জন্য আপনার চুক্তি গঠন করে।\n\n"
    "9. বিষয়বস্তু\n\n"
    "আমাদের পরিষেবা আপনাকে পোস্ট করতে, লিঙ্ক করতে, সঞ্চয় করতে, শেয়ার করতে এবং অন্যথায় কিছু তথ্য, পাঠ্য, গ্রাফিক্স, ভিডিও বা অন্যান্য উপাদান ('সামগ্রী') উপলব্ধ করতে দেয়৷ আপনি পরিষেবাতে বা এর মাধ্যমে যে সামগ্রী পোস্ট করেন তার বৈধতা, নির্ভরযোগ্যতা এবং উপযুক্ততা সহ আপনি তার জন্য দায়ী৷\n\n"
    "পরিষেবাতে বা এর মাধ্যমে বিষয়বস্তু পোস্ট করার মাধ্যমে, আপনি প্রতিনিধিত্ব করেন এবং ওয়ারেন্টি দেন যে: (i) বিষয়বস্তু আপনার (আপনি এটির মালিক) এবং/অথবা আপনার এটি ব্যবহার করার অধিকার এবং এই শর্তাবলীতে প্রদত্ত অধিকার এবং লাইসেন্স দেওয়ার অধিকার আপনার আছে , এবং (ii) পরিষেবাতে বা এর মাধ্যমে আপনার বিষয়বস্তুর পোস্ট করা গোপনীয়তার অধিকার, প্রচারের অধিকার, কপিরাইট, চুক্তির অধিকার বা কোনো ব্যক্তি বা সত্তার অন্য কোনো অধিকার লঙ্ঘন করে না। আমরা একটি কপিরাইট লঙ্ঘন করা খুঁজে পাওয়া যে কেউ অ্যাকাউন্ট বন্ধ করার অধিকার সংরক্ষিত.\n\n"
    "আপনার জমা দেওয়া, পোস্ট করা, বা পরিষেবাতে বা এর মাধ্যমে প্রদর্শন করা যেকোন বিষয়বস্তুর যেকোনো এবং সমস্ত অধিকার আপনি বজায় রাখেন এবং সেই অধিকারগুলি রক্ষা করার জন্য আপনি দায়ী। আমরা কোন দায়বদ্ধতা নিই না এবং পরিষেবাতে বা এর মাধ্যমে আপনার বা কোনও তৃতীয় পক্ষের পোস্টের জন্য কোনও দায়বদ্ধতা গ্রহণ করি না। যাইহোক, পরিষেবা ব্যবহার করে বিষয়বস্তু পোস্ট করার মাধ্যমে আপনি আমাদের পরিষেবাতে এবং এর মাধ্যমে এই ধরনের সামগ্রী ব্যবহার, সংশোধন, সর্বজনীনভাবে সম্পাদন, সর্বজনীনভাবে প্রদর্শন, পুনরুত্পাদন এবং বিতরণ করার অধিকার এবং লাইসেন্স প্রদান করেন। আপনি সম্মত হন যে এই লাইসেন্সের মধ্যে আমাদের আপনার বিষয়বস্তু পরিষেবার অন্যান্য ব্যবহারকারীদের কাছে উপলব্ধ করার অধিকার অন্তর্ভুক্ত রয়েছে, যারা এই শর্তাবলী সাপেক্ষে আপনার সামগ্রী ব্যবহার করতে পারে৷\n\n"
    "Jibika Intelligic Ltd. এর অধিকার আছে কিন্তু ব্যবহারকারীদের দ্বারা প্রদত্ত সমস্ত বিষয়বস্তু নিরীক্ষণ ও সম্পাদনা করার বাধ্যবাধকতা নেই৷\n\n"
    "এছাড়াও, এই পরিষেবাতে বা এর মাধ্যমে পাওয়া বিষয়বস্তু জিবিকা ইন্টেলিজিক লিমিটেডের সম্পত্তি বা অনুমতি নিয়ে ব্যবহার করা হয়েছে। আপনি সম্পূর্ণ বা আংশিকভাবে, বাণিজ্যিক উদ্দেশ্যে বা ব্যক্তিগত লাভের জন্য, স্পষ্ট অগ্রিম লিখিত ব্যতীত উক্ত বিষয়বস্তু বিতরণ, পরিবর্তন, প্রেরণ, পুনরায় ব্যবহার, ডাউনলোড, পুনরায় পোস্ট, অনুলিপি বা ব্যবহার করতে পারবেন না।\n\n"
    "10. নিষিদ্ধ ব্যবহার\n\n"
    "আপনি শুধুমাত্র আইনানুগ উদ্দেশ্যে এবং শর্তাবলী অনুযায়ী পরিষেবা ব্যবহার করতে পারেন। আপনি পরিষেবা ব্যবহার না করতে সম্মত হন:\n\n"
    "0.1 যে কোনও উপায়ে যে কোনও প্রযোজ্য জাতীয় বা আন্তর্জাতিক আইন বা প্রবিধান লঙ্ঘন করে।\n\n"
    "0.2। অপ্রাপ্তবয়স্কদের অনুপযুক্ত বিষয়বস্তু বা অন্যথায় প্রকাশ করার মাধ্যমে শোষণ, ক্ষতি, বা শোষণ বা ক্ষতি করার চেষ্টা করার উদ্দেশ্যে।\n\n"
    "0.3। যেকোন “জাঙ্ক মেইল”, “চেইন লেটার,” “স্প্যাম” বা অন্য কোন অনুরূপ অনুরোধ সহ যেকোন বিজ্ঞাপন বা প্রচারমূলক সামগ্রী প্রেরণ বা প্রেরণের জন্য।\n\n"
    "0.4 কোম্পানি, কোম্পানির কর্মচারী, অন্য ব্যবহারকারী, বা অন্য কোনো ব্যক্তি বা সত্তাকে ছদ্মবেশী করা বা ছদ্মবেশী করার চেষ্টা করা।\n\n"
    "0.5। যে কোনো উপায়ে অন্যের অধিকার লঙ্ঘন করে, বা যেকোনো উপায়ে বেআইনি, হুমকি, প্রতারণামূলক, বা ক্ষতিকারক, বা কোনো বেআইনি, অবৈধ, প্রতারণামূলক, বা ক্ষতিকারক উদ্দেশ্য বা কার্যকলাপের সাথে সম্পর্কিত।\n\n"
    "0.6। অন্য কোনো আচরণে জড়িত হওয়া যা কারো ব্যবহার বা পরিষেবার উপভোগকে সীমাবদ্ধ বা বাধা দেয়, বা যা, আমাদের দ্বারা নির্ধারিত, কোম্পানি বা পরিষেবা ব্যবহারকারীদের ক্ষতি বা অসন্তুষ্ট করতে পারে বা তাদের দায়বদ্ধতার মুখোমুখি হতে পারে।\n\n"
    "11. উপরন্তু, আপনি সম্মত হন না:\n\n"
    "0.1 পরিষেবার মাধ্যমে রিয়েল-টাইম ক্রিয়াকলাপগুলিতে নিযুক্ত হওয়ার ক্ষমতা সহ পরিষেবাটি অক্ষম, অতিরিক্ত বোঝা, ক্ষতি বা পরিষেবাকে ক্ষতিগ্রস্থ করতে বা অন্য কোনও পক্ষের পরিষেবা ব্যবহারে হস্তক্ষেপ করতে পারে এমন কোনও উপায়ে পরিষেবা ব্যবহার করুন৷\n\n"
    "0.2। পরিষেবার যে কোনও উপাদান পর্যবেক্ষণ বা অনুলিপি করা সহ যে কোনও উদ্দেশ্যে পরিষেবা অ্যাক্সেস করার জন্য যে কোনও রোবট, মাকড়সা বা অন্য স্বয়ংক্রিয় ডিভাইস, প্রক্রিয়া বা উপায় ব্যবহার করুন।\n\n"
    "0.3। আমাদের পূর্ব লিখিত সম্মতি ব্যতীত পরিষেবাতে বা অন্য কোনও অননুমোদিত উদ্দেশ্যে নিরীক্ষণ বা অনুলিপি করার জন্য যে কোনও ম্যানুয়াল প্রক্রিয়া ব্যবহার করুন।\n\n"
    "0.4 যেকোন ডিভাইস, সফ্টওয়্যার বা রুটিন ব্যবহার করুন যা পরিষেবার সঠিক কাজে হস্তক্ষেপ করে।\n\n"
    "0.5। যে কোনো ভাইরাস, ট্রোজান হর্স, ওয়ার্ম, লজিক বোমা বা অন্যান্য উপাদানের পরিচয় দিন যা দূষিত বা প্রযুক্তিগতভাবে ক্ষতিকর।\n\n"
    "0.6। পরিষেবার যে কোনও অংশে, পরিষেবাটি যে সার্ভারে সংরক্ষণ করা হয়েছে, বা পরিষেবার সাথে সংযুক্ত যে কোনও সার্ভার, কম্পিউটার বা ডেটাবেসে অননুমোদিত অ্যাক্সেস, হস্তক্ষেপ, ক্ষতি বা ব্যাহত করার চেষ্টা করা।\n\n"
    "0.7। অ্যাটাক সার্ভিস একটি ডিনায়াল-অফ-সার্ভিস অ্যাটাক বা ডিস্ট্রিবিউটেড ডিনায়াল-অফ-সার্ভিস অ্যাটাকের মাধ্যমে।\n\n"
    "0.8। কোম্পানি রেটিং ক্ষতি বা মিথ্যা হতে পারে যে কোনো পদক্ষেপ নিন.\n\n"
    "0.9 অন্যথায় পরিষেবার সঠিক কাজে হস্তক্ষেপ করার চেষ্টা করুন।\n\n"
    "12. বিশ্লেষণ\n\n"
    "আমরা আমাদের পরিষেবার ব্যবহার নিরীক্ষণ এবং বিশ্লেষণ করতে তৃতীয় পক্ষের পরিষেবা প্রদানকারীদের ব্যবহার করতে পারি।\n\n"
    "অপ্রাপ্তবয়স্কদের দ্বারা কোন ব্যবহার নেই\n\n"
    "পরিষেবাটি শুধুমাত্র কমপক্ষে আঠারো (18) বছর বয়সী ব্যক্তিদের দ্বারা অ্যাক্সেস এবং ব্যবহারের জন্য উদ্দিষ্ট। পরিষেবা অ্যাক্সেস করে বা ব্যবহার করে, আপনি ওয়ারেন্টি দেন এবং প্রতিনিধিত্ব করেন যে আপনার বয়স কমপক্ষে আঠারো (18) বছর এবং এই চুক্তিতে প্রবেশ করার এবং শর্তাবলীর সমস্ত শর্তাবলী মেনে চলার সম্পূর্ণ কর্তৃত্ব, অধিকার এবং ক্ষমতা সহ। আপনার বয়স কমপক্ষে আঠারো (18) বছর না হলে, আপনি পরিষেবার অ্যাক্সেস এবং ব্যবহার উভয়ই নিষিদ্ধ।\n\n"
    "13. হিসাব\n\n"
    "আপনি যখন আমাদের সাথে একটি অ্যাকাউন্ট তৈরি করেন, আপনি গ্যারান্টি দেন যে আপনার বয়স 18 বছরের বেশি এবং আপনি আমাদের যে তথ্য প্রদান করেন তা সর্বদা সঠিক, সম্পূর্ণ এবং বর্তমান। ভুল, অসম্পূর্ণ বা অপ্রচলিত তথ্যের ফলে পরিষেবাতে আপনার অ্যাকাউন্ট অবিলম্বে বন্ধ হয়ে যেতে পারে।\n\n"
    "আপনার অ্যাকাউন্ট এবং পাসওয়ার্ডের গোপনীয়তা বজায় রাখার জন্য আপনি দায়ী, আপনার কম্পিউটার এবং/অথবা অ্যাকাউন্টে অ্যাক্সেসের সীমাবদ্ধতা সহ কিন্তু সীমাবদ্ধ নয়। আপনি আপনার অ্যাকাউন্ট এবং/অথবা পাসওয়ার্ডের অধীনে ঘটতে থাকা যেকোনো এবং সমস্ত কার্যকলাপ বা কর্মের জন্য দায় স্বীকার করতে সম্মত হন, আপনার পাসওয়ার্ড আমাদের পরিষেবা বা তৃতীয় পক্ষের পরিষেবার সাথে থাকুক না কেন। নিরাপত্তা লঙ্ঘন বা আপনার অ্যাকাউন্টের অননুমোদিত ব্যবহার সম্পর্কে সচেতন হওয়ার সাথে সাথে আপনাকে অবশ্যই আমাদেরকে অবহিত করতে হবে।\n\n"
    "আপনি একটি ব্যবহারকারীর নাম হিসাবে অন্য ব্যক্তি বা সত্তার নাম ব্যবহার করতে পারবেন না বা যেটি আইনত ব্যবহারের জন্য উপলব্ধ নয়, এমন একটি নাম বা ট্রেডমার্ক যা আপনি ছাড়া অন্য কোনো ব্যক্তি বা সত্তার অধিকারের অধীন, উপযুক্ত অনুমোদন ছাড়াই৷ আপনি আপত্তিকর, অশ্লীল বা অশ্লীল কোনো নাম ব্যবহারকারীর নাম হিসেবে ব্যবহার করতে পারবেন না।\n\n"
    "আমরা আমাদের নিজস্ব বিবেচনার ভিত্তিতে পরিষেবা প্রত্যাখ্যান করার, অ্যাকাউন্টগুলি বন্ধ করার, সামগ্রী অপসারণ বা সম্পাদনা করার বা অর্ডার বাতিল করার অধিকার সংরক্ষণ করি।\n\n"
    "14. বুদ্ধিবৃত্তিক সম্পত্তি\n\n"
    "পরিষেবা এবং এর মূল বিষয়বস্তু (ব্যবহারকারীদের দ্বারা সরবরাহ করা সামগ্রী ব্যতীত), বৈশিষ্ট্য এবং কার্যকারিতা জিবিকা ইন্টেলিজিক লিমিটেড এবং এর লাইসেন্সকারীদের একচেটিয়া সম্পত্তি এবং থাকবে। পরিষেবা কপিরাইট, ট্রেডমার্ক, এবং বিদেশী দেশের অন্যান্য আইন দ্বারা সুরক্ষিত। Jibika Intelligic Ltd.-এর পূর্ব লিখিত সম্মতি ছাড়া আমাদের ট্রেডমার্কগুলি কোনও পণ্য বা পরিষেবার সাথে ব্যবহার করা যাবে না।\n\n"
    "15. কপিরাইট নীতি\n\n"
    "আমরা অন্যদের মেধা সম্পত্তি অধিকার সম্মান. পরিষেবাতে পোস্ট করা বিষয়বস্তু যে কোনও ব্যক্তি বা সত্তার কপিরাইট বা অন্যান্য মেধা সম্পত্তি অধিকার ('লঙ্ঘন') লঙ্ঘন করে এমন কোনও দাবির প্রতিক্রিয়া জানানো আমাদের নীতি৷  আপনি যদি একজন কপিরাইট মালিক হন, বা একজনের পক্ষে অনুমোদিত হন, এবং আপনি বিশ্বাস করেন যে কপিরাইটযুক্ত কাজটি এমনভাবে অনুলিপি করা হয়েছে যা কপিরাইট লঙ্ঘন গঠন করে, অনুগ্রহ করে আপনার দাবিটি ইমেলের মাধ্যমে jibikaplexus@gmail.com-এ সাবজেক্ট লাইন সহ জমা দিন: 'কপিরাইট লঙ্ঘন' এবং আপনার দাবিতে 'কপিরাইট লঙ্ঘনের দাবির জন্য DMCA নোটিশ এবং পদ্ধতি' এর অধীনে বিশদ বিবরণ অনুযায়ী অভিযোগ লঙ্ঘনের একটি বিশদ বিবরণ অন্তর্ভুক্ত করুন।\n\n"
    "আপনার কপিরাইটে এবং/অথবা পরিষেবার মাধ্যমে পাওয়া যেকোন বিষয়বস্তুর লঙ্ঘনের জন্য ভুল উপস্থাপনা বা খারাপ-বিশ্বাসের দাবির জন্য ক্ষতির (খরচ এবং অ্যাটর্নিদের ফি সহ) জন্য আপনাকে দায়ী করা যেতে পারে।\n\n"
    "16. কপিরাইট লঙ্ঘন দাবির জন্য DMCA নোটিশ এবং পদ্ধতি\n\n"
    "আপনি আমাদের কপিরাইট এজেন্টকে লিখিতভাবে নিম্নলিখিত তথ্য প্রদান করে ডিজিটাল মিলেনিয়াম কপিরাইট আইন (DMCA) অনুসারে একটি বিজ্ঞপ্তি জমা দিতে পারেন (আরো বিস্তারিত জানার জন্য 17 U.S.C 512(c)(3) দেখুন):\n\n"
    "0.1 কপিরাইটের স্বার্থের মালিকের পক্ষে কাজ করার জন্য অনুমোদিত ব্যক্তির একটি বৈদ্যুতিন বা শারীরিক স্বাক্ষর;\n\n"
    "0.2। কপিরাইটযুক্ত কাজের একটি বিবরণ যা আপনি দাবি করেন যে লঙ্ঘন করা হয়েছে, যেখানে কপিরাইটযুক্ত কাজটি রয়েছে সেই অবস্থানের URL (যেমন, ওয়েব পৃষ্ঠার ঠিকানা) বা কপিরাইটযুক্ত কাজের একটি অনুলিপি সহ;\n\n"
    "0.3। URL এর সনাক্তকরণ বা পরিষেবার অন্যান্য নির্দিষ্ট অবস্থান যেখানে আপনি লঙ্ঘনকারী বলে দাবি করেন এমন উপাদানটি অবস্থিত;\n\n"
    "0.4 আপনার ঠিকানা, টেলিফোন নম্বর, এবং ইমেল ঠিকানা;\n\n"
    "0.5। আপনার দ্বারা একটি বিবৃতি যে আপনি একটি ভাল বিশ্বাস আছে যে বিতর্কিত ব্যবহার কপিরাইট মালিক, এর এজেন্ট, বা আইন দ্বারা অনুমোদিত নয়;\n\n"
    "0.6। আপনার দ্বারা একটি বিবৃতি, মিথ্যাচারের শাস্তির অধীনে প্রণীত, যে আপনার নোটিশের উপরোক্ত তথ্য সঠিক এবং আপনি কপিরাইটের মালিক বা কপিরাইট মালিকের পক্ষে কাজ করার জন্য অনুমোদিত।\n\n"
    "আপনি jibikaplexus@gmail.com এ ইমেলের মাধ্যমে আমাদের কপিরাইট এজেন্টের সাথে যোগাযোগ করতে পারেন।\n\n"
    "17. ত্রুটি রিপোর্টিং এবং প্রতিক্রিয়া\n\n"
    "আপনি আমাদের সরাসরি jibikaplexus@gmail.com এ অথবা তৃতীয় পক্ষের সাইট এবং টুলের মাধ্যমে ত্রুটি, উন্নতির জন্য পরামর্শ, ধারণা, সমস্যা, অভিযোগ এবং আমাদের পরিষেবার সাথে সম্পর্কিত অন্যান্য বিষয় (“প্রতিক্রিয়া”) সংক্রান্ত তথ্য এবং প্রতিক্রিয়া সহ আমাদের প্রদান করতে পারেন। আপনি স্বীকার করেন এবং সম্মত হন যে: (i) আপনি কোনো বুদ্ধিবৃত্তিক সম্পত্তির অধিকার বা অন্য অধিকার, শিরোনাম, বা প্রতিক্রিয়াতে বা আগ্রহ বজায় রাখতে, অর্জন করতে বা জোরদার করবেন না; (ii) কোম্পানি ফিডব্যাকের অনুরূপ ধারণা তৈরি করতে পারে; (iii) প্রতিক্রিয়া আপনার বা কোন তৃতীয় পক্ষের কাছ থেকে গোপনীয় তথ্য বা মালিকানাধীন তথ্য ধারণ করে না; এবং (iv) কোম্পানির প্রতিক্রিয়ার ক্ষেত্রে গোপনীয়তার কোনো বাধ্যবাধকতা নেই। প্রযোজ্য বাধ্যতামূলক আইনের কারণে ফিডব্যাকে মালিকানা হস্তান্তর করা সম্ভব না হলে, আপনি কোম্পানি এবং এর সহযোগীদের একটি একচেটিয়া, হস্তান্তরযোগ্য, অপরিবর্তনীয়, বিনামূল্যের, উপ-লাইসেন্সযোগ্য, সীমাহীন এবং চিরস্থায়ী ব্যবহারের অধিকার প্রদান করেন। (কপি, পরিবর্তন, ডেরিভেটিভ কাজ তৈরি, প্রকাশ, বিতরণ এবং বাণিজ্যিকীকরণ সহ) যে কোনও উপায়ে এবং যে কোনও উদ্দেশ্যে প্রতিক্রিয়া।\n\n"
    "18. অন্যান্য ওয়েব সাইটের লিঙ্ক\n\n"
    "আমাদের পরিষেবাতে তৃতীয় পক্ষের ওয়েবসাইট বা পরিষেবাগুলির লিঙ্ক থাকতে পারে যেগুলি জিবিকা ইন্টেলিজিক লিমিটেডের মালিকানাধীন বা নিয়ন্ত্রিত নয়৷\n\n"
    "Jibika Intelligic Ltd. এর কোনো নিয়ন্ত্রণ নেই এবং কোনো তৃতীয় পক্ষের ওয়েবসাইট বা পরিষেবার বিষয়বস্তু, গোপনীয়তা নীতি বা অনুশীলনের জন্য কোনো দায়বদ্ধতা নেই। আমরা এই সত্ত্বা/ব্যক্তি বা তাদের ওয়েবসাইটের কোনো প্রস্তাবের ওয়ারেন্টি দিই না..\n\n"
    "আপনি স্বীকার করেন এবং সম্মত হন যে সংস্থাটি প্রত্যক্ষভাবে বা পরোক্ষভাবে, কোনও ক্ষতি বা ক্ষতির জন্য দায়ী বা দায়বদ্ধ হবে না, যে কোনও ক্ষতি বা ক্ষতির কারণ হতে পারে বা কথিত যে কোনও কারণে, আমাদের পক্ষ থেকে বা দায়বদ্ধতার কারণে বা এই জাতীয় যেকোন তৃতীয় পক্ষের ওয়েব সাইট বা পরিষেবাগুলির মাধ্যমে।\n\n"
    "আমরা আপনাকে দৃঢ়ভাবে পরামর্শ দিচ্ছি যে আপনি যেকোন থার্ড-পার্টি ওয়েবসাইট বা পরিষেবাগুলির পরিষেবার শর্তাবলী এবং গোপনীয়তা নীতিগুলি পড়ুন যা আপনি পরিদর্শন করেন৷\n\n"
    "19. ওয়ারেন্টি অস্বীকৃতি\n\n"
    "এই পরিষেবাগুলি একটি 'যেমন আছে' এবং 'যেমন উপলব্ধ' ভিত্তিতে কোম্পানি দ্বারা প্রদান করা হয়৷ কোম্পানি তাদের পরিষেবার ক্রিয়াকলাপ, বা এতে অন্তর্ভুক্ত তথ্য, বিষয়বস্তু, বা উপকরণগুলির জন্য কোনও ধরণের, প্রকাশ বা উহ্য কোনও প্রতিনিধিত্ব বা ওয়ারেন্টি দেয় না৷ আপনি স্পষ্টভাবে সম্মত হন যে এই পরিষেবাগুলির আপনার ব্যবহার, তাদের বিষয়বস্তু এবং আমাদের থেকে প্রাপ্ত যেকোনো পরিষেবা বা আইটেম আপনার সম্পূর্ণ ঝুঁকিতে৷\n\n"
    "সম্পূর্ণতা, নিরাপত্তা, নির্ভরযোগ্যতা, গুণমান, নির্ভুলতা, বা উপলভ্যতার ক্ষেত্রে কোম্পানি বা কোম্পানির সাথে যুক্ত কোনো ব্যক্তিই কোনো ওয়্যারেন্টি বা উপস্থাপনা করে না। পূর্বোক্তকে সীমাবদ্ধ না করে, সংস্থার সাথে যুক্ত সংস্থা বা কেউই বা ওয়ারেন্টের প্রতিনিধিত্ব করে না যে পরিষেবাগুলি, তাদের সামগ্রী, বা পরিষেবাগুলির মাধ্যমে প্রাপ্ত কোনও পরিষেবা বা আইটেমগুলি সঠিক, নির্ভরযোগ্য, ত্রুটিমুক্ত বা নিরবচ্ছিন্ন হবে, ত্রুটিগুলি সংশোধন করা হবে , যে পরিষেবাগুলি বা সার্ভার যা এটিকে উপলব্ধ করে সেগুলি ভাইরাস বা অন্যান্য ক্ষতিকারক উপাদানগুলি বা পরিষেবাগুলি বা পরিষেবাগুলি বা পরিষেবাগুলি বা আইটেমগুলি মুক্ত৷\n\n"
    "কোম্পানী এতদ্বারা যে কোন প্রকারের সকল ওয়্যারেন্টি অস্বীকার করে, তা প্রকাশ বা উহ্য, সংবিধিবদ্ধ, বা অন্যথায়, বণিকযোগ্যতার কোন ওয়্যারেন্টি সহ কিন্তু সীমাবদ্ধ নয়।\n\n"
    "পূর্বোক্ত কোনো ওয়্যারেন্টিকে প্রভাবিত করে না যা প্রযোজ্য আইনের অধীনে বাদ দেওয়া বা সীমিত করা যাবে না।\n\n\n"
    "20. দায়বদ্ধতার সীমাবদ্ধতা\n\n"
    "আইন দ্বারা নিষিদ্ধ ব্যতীত, আপনি আমাদের এবং আমাদের কর্মকর্তাদের, পরিচালকদের, কর্মচারীদের এবং এজেন্টদেরকে যে কোনো পরোক্ষ, শাস্তিমূলক, বিশেষ, ঘটনাক্রমে, বা পরবর্তিতে, পরবর্তিতে, পরোক্ষভাবে ধারণ করবেন মোকদ্দমা এবং সালিশ, বা বিচারে বা আপিলের সময়, যদি কোনো, মোকদ্দমা বা সালিস প্রতিষ্ঠিত হয় বা না করা হয়), চুক্তির কোনো কর্মে, অবহেলা, বা অন্য কোনো আইনগত অভিযোগ, আইনগত অভিযোগ এই চুক্তি থেকে উদ্ভূত ব্যক্তিগত আঘাত বা সম্পত্তির ক্ষতির সীমাবদ্ধতা ছাড়াই কোনো দাবি এবং আপনার দ্বারা যেকোনো ফেডারেল, স্টেট, বা স্থানীয় আইন, বিধি-বিধান, প্রাতিষ্ঠানিক প্রশাসনিক আইনের লঙ্ঘন ক্ষতি। আইন দ্বারা নিষিদ্ধ ব্যতীত, যদি কোম্পানির পক্ষ থেকে দায়বদ্ধতা পাওয়া যায়, তবে এটি পণ্য এবং/অথবা পরিষেবাগুলির জন্য প্রদত্ত অর্থের মধ্যে সীমাবদ্ধ থাকবে এবং অনিয়ন্ত্রিত ক্ষতিসাধনে ক্ষতিগ্রস্থ হবে না৷ কিছু রাজ্য শাস্তিমূলক, আকস্মিক, বা ফলস্বরূপ ক্ষতির বর্জন বা সীমাবদ্ধতার অনুমতি দেয় না, তাই পূর্বের সীমাবদ্ধতা বা বর্জন আপনার জন্য প্রযোজ্য নাও হতে পারে।\n\n"
    "21. সমাপ্তি\n\n"
    "আমরা শর্তাবলী লঙ্ঘন সহ কিন্তু সীমাবদ্ধ নয় এমন যেকোন কারণে এবং সীমাবদ্ধতা ছাড়াই, আমাদের একমাত্র বিবেচনার অধীনে, পূর্ব বিজ্ঞপ্তি বা দায় ছাড়াই আপনার অ্যাকাউন্ট এবং পরিষেবাতে অ্যাক্সেস অবিলম্বে বন্ধ বা স্থগিত করতে পারি।\n\n"
    "আপনি যদি আপনার অ্যাকাউন্টটি বন্ধ করতে চান তবে আপনি কেবল পরিষেবাটি ব্যবহার করা বন্ধ করতে পারেন৷\n\n"
    "শর্তাবলীর সমস্ত বিধান যা তাদের প্রকৃতির দ্বারা সমাপ্তি থেকে বেঁচে থাকা উচিত, সীমাবদ্ধতা ছাড়াই, মালিকানা বিধান, ওয়ারেন্টি দাবিত্যাগ, ক্ষতিপূরণ এবং দায়বদ্ধতার সীমাবদ্ধতা সহ সমাপ্তি টিকে থাকবে।\n\n"
    "22. পরিচালনা আইন\n\n"
    "এই শর্তাদি নিয়ন্ত্রিত হবে এবং বাংলাদেশের আইন অনুযায়ী বোঝানো হবে, যে আইনের বিধানের বিরোধ বিবেচনা না করেই চুক্তিতে প্রযোজ্য।\n\n"
    "এই শর্তাবলীর কোন অধিকার বা বিধান কার্যকর করতে আমাদের ব্যর্থতা সেই অধিকারগুলির মওকুফ হিসাবে বিবেচিত হবে না। যদি এই শর্তাবলীর কোনো বিধান আদালত দ্বারা অবৈধ বা অপ্রয়োগযোগ্য বলে ধরা হয়, তবে এই শর্তাবলীর অবশিষ্ট বিধান কার্যকর থাকবে। এই শর্তাদি আমাদের পরিষেবা সম্পর্কিত আমাদের মধ্যে সম্পূর্ণ চুক্তি গঠন করে এবং পরিষেবার বিষয়ে আমাদের মধ্যে আমাদের মধ্যে থাকা পূর্ববর্তী চুক্তিগুলিকে বাতিল করে এবং প্রতিস্থাপন করে৷\n\n"
    "23. পরিষেবাতে পরিবর্তন\n\n"
    "আমরা আমাদের পরিষেবা প্রত্যাহার বা সংশোধন করার অধিকার সংরক্ষণ করি, এবং আমরা পরিষেবার মাধ্যমে যে কোনও পরিষেবা বা উপাদান প্রদান করি, আমাদের নিজস্ব বিবেচনার ভিত্তিতে বিজ্ঞপ্তি ছাড়াই৷ আমরা দায়বদ্ধ থাকব না যদি কোনও কারণে পরিষেবার সমস্ত বা কোনও অংশ যে কোনও সময়ে বা কোনও সময়ের জন্য অনুপলব্ধ হয়। সময়ে সময়ে, আমরা নিবন্ধিত ব্যবহারকারী সহ ব্যবহারকারীদের জন্য পরিষেবার কিছু অংশ বা সম্পূর্ণ পরিষেবার অ্যাক্সেস সীমাবদ্ধ করতে পারি।\n\n"
    "24. শর্তাবলী সংশোধন\n\n"
    "আমরা এই সাইটে সংশোধিত শর্তাবলী পোস্ট করে যেকোনো সময় শর্তাবলী সংশোধন করতে পারি। পর্যায়ক্রমে এই শর্তাবলী পর্যালোচনা করা আপনার দায়িত্ব।\n\n"
    "সংশোধিত শর্তাবলী পোস্ট করার পরে প্ল্যাটফর্মের আপনার ক্রমাগত ব্যবহার এর অর্থ হল আপনি পরিবর্তনগুলি স্বীকার করেন এবং সম্মত হন। আপনি এই পৃষ্ঠাটি ঘন ঘন পরীক্ষা করবেন বলে আশা করা হচ্ছে যাতে আপনি কোনো পরিবর্তন সম্পর্কে সচেতন হন, কারণ সেগুলি আপনার জন্য বাধ্য।\n\n"
    "কোনো সংশোধন কার্যকর হওয়ার পরে আমাদের পরিষেবা অ্যাক্সেস বা ব্যবহার চালিয়ে যাওয়ার মাধ্যমে, আপনি সংশোধিত শর্তাবলী দ্বারা আবদ্ধ হতে সম্মত হন। আপনি যদি নতুন শর্তাবলীতে সম্মত না হন তবে আপনি আর পরিষেবাটি ব্যবহার করার জন্য অনুমোদিত নন৷\n\n"
    "25. মওকুফ এবং বিচ্ছিন্নতা\n\n"
    "শর্তাবলীতে বর্ণিত কোন শর্ত বা শর্তের কোম্পানির দ্বারা কোন মওকুফ এই ধরনের মেয়াদ বা শর্তের আরও বা অব্যাহত মওকুফ বা অন্য কোন শর্ত বা শর্তের মওকুফ, এবং শর্তাবলীর অধীনে একটি অধিকার বা বিধান জাহির করতে কোম্পানির কোন ব্যর্থতা বলে গণ্য হবে না এই ধরনের অধিকার বা বিধান একটি মওকুফ গঠন করা হবে না.\n\n"
    "যদি শর্তাবলীর কোনো বিধান কোনো আদালত বা উপযুক্ত এখতিয়ারের অন্য ট্রাইব্যুনাল দ্বারা অবৈধ, অবৈধ বা কোনো কারণে অপ্রয়োগযোগ্য বলে ধরে রাখা হয়, তাহলে এই ধরনের বিধান বাদ দেওয়া হবে বা ন্যূনতম পরিমাণে সীমিত হবে যাতে শর্তাবলীর অবশিষ্ট বিধানগুলি সম্পূর্ণরূপে চলতে থাকবে। বল এবং প্রভাব।\n\n"
    "26. স্বীকৃতি\n\n"
    "আমাদের দ্বারা প্রদত্ত পরিষেবা বা অন্যান্য পরিষেবাগুলি ব্যবহার করে, আপনি স্বীকার করেন যে আপনি এই পরিষেবার শর্তাবলী পড়েছেন এবং তাদের দ্বারা আবদ্ধ হতে সম্মত হন৷\n\n"
    "27. আমাদের সাথে যোগাযোগ করুন\n\n"
    "অনুগ্রহ করে আপনার মতামত, মন্তব্য এবং প্রযুক্তিগত সহায়তার জন্য অনুরোধ পাঠান ইমেলের মাধ্যমে: jibikaplexus@gmail.com।";