import 'dart:core';

const String date ="Effective date: 2023-03-27\n";
const String datebn ="কার্যকরী তারিখ: 2023-03-27\n";
const String intro="1. Introduction\n";
const String introbn ="1। পরিচিতি\n";
const String introbrief="Welcome to Jibika Intelligic Ltd..\n\n"
    "Jibika Intelligic Ltd. (“us”, “we”, or “our”) \n\n"
    "operates www.jibikaplexus.com (hereinafter referred to as “Service”).\n\n"
    "Our Privacy Policy governs your visit to www.jibikaplexus.com, and explains how we collect, safeguard and disclose information that results from your use of our Service.\n\n"
    "We use your data to provide and improve Service. By using Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.\n\n"
    "Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitutes your agreement with us (“agreement”).\n\n";
const String introbriefbn="জিবিকা ইন্টেলিজিক লিমিটেডে স্বাগতম।\n\n"
    "জিবিকা ইন্টেলিজিক লিমিটেড (“আমাদের”, “আমরা”, বা “আমাদের”) www.jibikaplexus.com পরিচালনা করে (এরপরে “পরিষেবা” হিসাবে উল্লেখ করা হয়েছে)।\n\n"
    "আমাদের গোপনীয়তা নীতি www.jibikaplexus.com-এ আপনার পরিদর্শনকে নিয়ন্ত্রণ করে এবং ব্যাখ্যা করে যে আমরা কীভাবে তথ্য সংগ্রহ করি, রক্ষা করি এবং প্রকাশ করি যা আপনার আমাদের পরিষেবা ব্যবহারের ফলে ফলাফল হয়।\n\n"
    "আমরা পরিষেবা প্রদান এবং উন্নত করতে আপনার ডেটা ব্যবহার করি। পরিষেবা ব্যবহার করে, আপনি এই নীতি অনুসারে তথ্য সংগ্রহ এবং ব্যবহারে সম্মত হন। এই গোপনীয়তা নীতিতে অন্যথায় সংজ্ঞায়িত না থাকলে, এই গোপনীয়তা নীতিতে ব্যবহৃত শর্তাবলীর অর্থ আমাদের শর্তাবলীর মতোই রয়েছে৷\n\n"
    "আমাদের শর্তাবলী ('শর্তাবলী') আমাদের পরিষেবার সমস্ত ব্যবহার নিয়ন্ত্রণ করে এবং গোপনীয়তা নীতির সাথে আমাদের সাথে আপনার চুক্তি ('চুক্তি') গঠন করে।\n\n";
const String defination="Definitions,\n";
const String definationbn="সংজ্ঞা\n";
const String defibrief="SERVICE means the www.jibikaplexus.com website operated by Jibika Intelligic Ltd..\n\n"
    "PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).\n\n"
    "USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).\n\n"
    "COOKIES are small files stored on your device (computer or mobile device).\n\n"
    "DATA CONTROLLER means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.\n\n"
    "DATA PROCESSORS (OR SERVICE PROVIDERS) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.\n\n"
    "DATA SUBJECT is any living individual who is the subject of Personal Data.\n\n"
    "THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.\n\n";
const String defibriefbn="পরিষেবা মানে Jibika Intelligic Ltd. দ্বারা পরিচালিত www.jibikaplexus.com ওয়েবসাইট।\n\n"
    "ব্যক্তিগত ডেটা মানে একজন জীবিত ব্যক্তির সম্পর্কে ডেটা যাকে সেই ডেটা থেকে শনাক্ত করা যেতে পারে (বা সেগুলি এবং অন্যান্য তথ্য হয় আমাদের দখলে বা আমাদের দখলে আসতে পারে)।\n\n"
    "USAGE ডেটা হল পরিষেবার ব্যবহার বা পরিষেবা পরিকাঠামো থেকে স্বয়ংক্রিয়ভাবে সংগৃহীত ডেটা (উদাহরণস্বরূপ, একটি পৃষ্ঠা দেখার সময়কাল)।\n\n"
    "কুকি হল আপনার ডিভাইসে (কম্পিউটার বা মোবাইল ডিভাইস) সংরক্ষিত ছোট ফাইল।\n\n"
    "ডেটা কন্ট্রোলার মানে একজন প্রাকৃতিক বা আইনী ব্যক্তি যিনি (হয় একা বা যৌথভাবে বা অন্য ব্যক্তির সাথে সাধারণ) কোন ব্যক্তিগত ডেটা প্রক্রিয়াকরণের উদ্দেশ্যে এবং পদ্ধতিতে নির্ধারণ করেন। এই গোপনীয়তা নীতির উদ্দেশ্যে, আমরা আপনার ডেটার একটি ডেটা কন্ট্রোলার।\n\n"
    "ডেটা প্রসেসর (বা পরিষেবা প্রদানকারী) মানে যে কোনও প্রাকৃতিক বা আইনি ব্যক্তি যিনি ডেটা কন্ট্রোলারের হয়ে ডেটা প্রক্রিয়া করেন৷ আপনার ডেটা আরও কার্যকরভাবে প্রক্রিয়া করার জন্য আমরা বিভিন্ন পরিষেবা প্রদানকারীর পরিষেবাগুলি ব্যবহার করতে পারি।\n\n"
    "DATA SUBJECT হল যে কোনও জীবিত ব্যক্তি যিনি ব্যক্তিগত ডেটার বিষয়।\n\n"
    "ব্যবহারকারী আমাদের পরিষেবা ব্যবহারকারী ব্যক্তি। ব্যবহারকারী ডেটা বিষয়ের সাথে সম্পর্কিত, যিনি ব্যক্তিগত ডেটার বিষয়।\n\n";
const String infocollection="Information Collection and Use\n\n";
const String infocollectionbn="তথ্য সংগ্রহ এবং ব্যবহার\n\n";
const String infocolbrf="We collect several different types of information for various purposes to provide and improve our Service to you.\n\n";
const String infocolbrfbn="আমরা আপনাকে আমাদের পরিষেবা প্রদান এবং উন্নত করতে বিভিন্ন উদ্দেশ্যে বিভিন্ন ধরণের তথ্য সংগ্রহ করি।\n\n";


const String typofdata="4. Types of Data Collected\n\n";
const String typofdatabn="4. সংগৃহীত তথ্যের প্রকার";
const String typeofdatabrf="Personal Data\n\n"
    "While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:\n\n"
    "0.1. Email address\n\n"
    "0.2. First name and last name\n\n"
    "0.3. Phone number\n\n"
    "0.4. Address, Country, State, Province, ZIP/Postal code, City\n\n"
    "0.5. Cookies and Usage Data\n\n"
    "We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link.\n\n"
    "Usage Data\n\n"
    "We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through any device (“Usage Data”).\n\n"
    "This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.\n\n"
    "When you access Service with a device, this Usage Data may include information such as the type of device you use, your device unique ID, the IP address of your device, your device operating system, the type of Internet browser you use, unique device identifiers and other diagnostic data.\n\n"
    "Location Data\n\n"
    "We may use and store information about your location if you give us permission to do so (“Location Data”). We use this data to provide features of our Service, to improve and customize our Service.\n\n"
    "You can enable or disable location services when you use our Service at any time by way of your device settings.\n\n"
    "Tracking Cookies Data\n\n"
    "We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.\n\n"
    "Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyze our Service.\n\n"
    "You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.\n\n"
    "Examples of Cookies we use:\n\n"
    "0.1. Session Cookies: We use Session Cookies to operate our Service.\n\n"
    "0.2. Preference Cookies: We use Preference Cookies to remember your preferences and various settings.\n\n"
    "0.3. Security Cookies: We use Security Cookies for security purposes\n\n"
    "0.4. Advertising Cookies: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.\n\n"
    "Other Data\n\n"
    "While using our Service, we may also collect the following information: sex, age, date of birth, place of birth, passport details, citizenship, registration at place of residence and actual address, telephone number (work, mobile), details of documents on education, qualification, professional training, employment agreements, NDA agreements, information on bonuses and compensation, information on marital status, family members, social security (or other taxpayer identification) number, office location and other data.\n\n"
    "";
const String typeofdatabrfbn="ব্যক্তিগত তথ্য\n\n"
    "আমাদের পরিষেবা ব্যবহার করার সময়, আমরা আপনাকে কিছু ব্যক্তিগতভাবে শনাক্তযোগ্য তথ্য সরবরাহ করতে বলতে পারি যা আপনার সাথে যোগাযোগ করতে বা সনাক্ত করতে ব্যবহার করা যেতে পারে (“ব্যক্তিগত ডেটা”)। ব্যক্তিগতভাবে সনাক্তযোগ্য তথ্য অন্তর্ভুক্ত হতে পারে, কিন্তু সীমাবদ্ধ নয়:\n\n"
    "0.1 ইমেইল ঠিকানা\n\n"
    "0.2। প্রথম নাম এবং শেষ নাম\n\n"
    "0.3। ফোন নম্বর\n\n"
    "0.4 ঠিকানা, দেশ, রাজ্য, প্রদেশ, জিপ/পোস্টাল কোড, শহর\n\n"
    "0.5। কুকিজ এবং ব্যবহার তথ্য\n\n"
    "আমরা নিউজলেটার, বিপণন বা প্রচারমূলক উপকরণ এবং আপনার আগ্রহের হতে পারে এমন অন্যান্য তথ্যের সাথে আপনার সাথে যোগাযোগ করতে আপনার ব্যক্তিগত ডেটা ব্যবহার করতে পারি। আপনি আনসাবস্ক্রাইব লিঙ্কটি অনুসরণ করে আমাদের কাছ থেকে এই সমস্ত যোগাযোগগুলি গ্রহণ করা থেকে অপ্ট আউট করতে পারেন৷\n\n"
    "ব্যবহারের ডেটা\n\n"
    "আপনি যখনই আমাদের পরিষেবা পরিদর্শন করেন বা যখন আপনি কোনও ডিভাইস ('ব্যবহারের ডেটা') এর মাধ্যমে পরিষেবা অ্যাক্সেস করেন তখন আমরা আপনার ব্রাউজার যে তথ্য পাঠায় তা সংগ্রহ করতে পারি।\n"
    "এই ব্যবহারের ডেটাতে আপনার কম্পিউটারের ইন্টারনেট প্রোটোকল ঠিকানা (যেমন আইপি ঠিকানা), ব্রাউজারের ধরন, ব্রাউজারের সংস্করণ, আমাদের পরিষেবার পৃষ্ঠাগুলি যেগুলি আপনি পরিদর্শন করেন, আপনার দর্শনের সময় এবং তারিখ, সেই পৃষ্ঠাগুলিতে ব্যয় করা সময়, অনন্য ইত্যাদি তথ্য অন্তর্ভুক্ত থাকতে পারে ডিভাইস শনাক্তকারী এবং অন্যান্য ডায়গনিস্টিক ডেটা।\n\n"
    "যখন আপনি একটি ডিভাইসের সাথে পরিষেবা অ্যাক্সেস করেন, তখন এই ব্যবহারের ডেটাতে আপনার ব্যবহার করা ডিভাইসের ধরন, আপনার ডিভাইসের অনন্য আইডি, আপনার ডিভাইসের আইপি ঠিকানা, আপনার ডিভাইস অপারেটিং সিস্টেম, আপনার ব্যবহার করা ইন্টারনেট ব্রাউজারের ধরন, অনন্য ডিভাইসের মতো তথ্য অন্তর্ভুক্ত থাকতে পারে শনাক্তকারী এবং অন্যান্য ডায়গনিস্টিক ডেটা।\n\n"
    "অবস্থান ডেটা\n\n"
    "আপনি যদি আমাদের অনুমতি দেন তবে আমরা আপনার অবস্থান সম্পর্কে তথ্য ব্যবহার এবং সংরক্ষণ করতে পারি ('অবস্থান ডেটা')। আমরা আমাদের পরিষেবার বৈশিষ্ট্যগুলি প্রদান করতে, আমাদের পরিষেবা উন্নত করতে এবং কাস্টমাইজ করতে এই ডেটা ব্যবহার করি।\n\n"
    "আপনি আপনার ডিভাইস সেটিংসের মাধ্যমে যেকোনো সময় আমাদের পরিষেবা ব্যবহার করার সময় অবস্থান পরিষেবাগুলি সক্ষম বা অক্ষম করতে পারেন৷\n\n"
    "ট্র্যাকিং কুকিজ ডেটা\n\n"
    "আমরা আমাদের পরিষেবার কার্যকলাপ ট্র্যাক করতে কুকিজ এবং অনুরূপ ট্র্যাকিং প্রযুক্তি ব্যবহার করি এবং আমরা কিছু তথ্য রাখি।\n\n"
    "কুকিজ হল অল্প পরিমাণ ডেটা সহ ফাইল যাতে একটি বেনামী অনন্য শনাক্তকারী অন্তর্ভুক্ত থাকতে পারে। কুকিজ একটি ওয়েবসাইট থেকে আপনার ব্রাউজারে পাঠানো হয় এবং আপনার ডিভাইসে সংরক্ষণ করা হয়। অন্যান্য ট্র্যাকিং প্রযুক্তিগুলিও ব্যবহার করা হয় যেমন বীকন, ট্যাগ এবং স্ক্রিপ্টগুলি তথ্য সংগ্রহ ও ট্র্যাক করতে এবং আমাদের পরিষেবার উন্নতি ও বিশ্লেষণ করতে।\n\n"
    "আপনি আপনার ব্রাউজারকে সমস্ত কুকি প্রত্যাখ্যান করতে বা কখন একটি কুকি পাঠানো হচ্ছে তা নির্দেশ করতে পারেন। যাইহোক, আপনি যদি কুকিজ গ্রহণ না করেন, তাহলে আপনি আমাদের পরিষেবার কিছু অংশ ব্যবহার করতে পারবেন না।\n\n"
    "আমরা যে কুকি ব্যবহার করি তার উদাহরণ:\n\n"
    "0.1 সেশন কুকিজ: আমরা আমাদের পরিষেবা পরিচালনা করতে সেশন কুকিজ ব্যবহার করি।\n\n"
    "0.2। পছন্দ কুকি: আমরা আপনার পছন্দ এবং বিভিন্ন সেটিংস মনে রাখতে পছন্দ কুকি ব্যবহার করি।\n\n"
    "0.3। নিরাপত্তা কুকি: আমরা নিরাপত্তার উদ্দেশ্যে নিরাপত্তা কুকি ব্যবহার করি।\n\n"
    "0.4 বিজ্ঞাপন কুকিজ: বিজ্ঞাপন কুকিগুলি আপনাকে বিজ্ঞাপন পরিবেশন করতে ব্যবহৃত হয় যা আপনার এবং আপনার আগ্রহের সাথে প্রাসঙ্গিক হতে পারে।\n\n"
    "অন্যান্য ডেটা\n\n"
    "আমাদের পরিষেবা ব্যবহার করার সময়, আমরা নিম্নলিখিত তথ্যও সংগ্রহ করতে পারি: লিঙ্গ, বয়স, জন্ম তারিখ, জন্মস্থান, পাসপোর্টের বিশদ বিবরণ, নাগরিকত্ব, বসবাসের স্থানে নিবন্ধন এবং প্রকৃত ঠিকানা, টেলিফোন নম্বর (কাজ, মোবাইল), নথির বিবরণ শিক্ষা, যোগ্যতা, পেশাদার প্রশিক্ষণ, কর্মসংস্থান চুক্তি, এনডিএ চুক্তি, বোনাস এবং ক্ষতিপূরণ সম্পর্কিত তথ্য, বৈবাহিক অবস্থার তথ্য, পরিবারের সদস্য, সামাজিক নিরাপত্তা (বা অন্যান্য করদাতা সনাক্তকরণ) নম্বর, অফিসের অবস্থান এবং অন্যান্য ডেটা।\n\n"
    "";


const String usedata="Use of Data\n\n";
const String usedatabn="ডেটা ব্যবহার";
const String usedatabrf="Jibika Intelligic Ltd. uses the collected data for various purposes:\n\n"
    "0.1. to provide and maintain our Service;\n\n"
    "0.2. to notify you about changes to our Service;\n\n"
    "0.3. to allow you to participate in interactive features of our Service when you choose to do so;\n\n"
    "0.4. to provide customer support;\n\n"
    "0.5. to gather analysis or valuable information so that we can improve our Service;\n\n"
    "0.6. to monitor the usage of our Service;\n\n"
    "0.7. to detect, prevent and address technical issues;\n\n"
    "0.8. to fulfil any other purpose for which you provide it;\n\n"
    "0.9. to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;\n\n"
    "0.10. to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;\n\n"
    "0.11. to provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;\n\n"
    "0.12. in any other way we may describe when you provide the information;\n\n"
    "0.13. for any other purpose with your consent.\n\n";
const String usedatabrfbn="Jibika Intelligic Ltd. বিভিন্ন উদ্দেশ্যে সংগৃহীত তথ্য ব্যবহার করে:\n\n"
    "0.1 আমাদের পরিষেবা প্রদান এবং বজায় রাখা;\n\n"
    "0.2। আমাদের পরিষেবার পরিবর্তন সম্পর্কে আপনাকে অবহিত করতে;\n\n"
    "0.3। আপনি যখন এটি করতে চান তখন আপনাকে আমাদের পরিষেবার ইন্টারেক্টিভ বৈশিষ্ট্যগুলিতে অংশগ্রহণ করার অনুমতি দিতে;\n\n"
    "0.4 গ্রাহক সহায়তা প্রদান;\n\n"
    "0.5। বিশ্লেষণ বা মূল্যবান তথ্য সংগ্রহ করতে যাতে আমরা আমাদের পরিষেবা উন্নত করতে পারি;\n\n"
    "0.6। আমাদের পরিষেবার ব্যবহার নিরীক্ষণ করতে;\n\n"
    "0.7। প্রযুক্তিগত সমস্যা সনাক্ত, প্রতিরোধ এবং সমাধান করা;\n\n"
    "0.8। আপনি এটি প্রদান করেন এমন অন্য কোনো উদ্দেশ্য পূরণ করতে;\n\n"
    "0.9 আমাদের বাধ্যবাধকতাগুলি পালন করা এবং বিলিং এবং সংগ্রহ সহ আপনার এবং আমাদের মধ্যে সম্পাদিত যে কোনও চুক্তি থেকে উদ্ভূত আমাদের অধিকারগুলি প্রয়োগ করা;\n\n"
    "0.10 আপনাকে আপনার অ্যাকাউন্ট এবং/অথবা সাবস্ক্রিপশন সম্পর্কে নোটিশ প্রদান করতে, যার মধ্যে মেয়াদ শেষ হওয়া এবং পুনর্নবীকরণের বিজ্ঞপ্তি, ইমেল-নির্দেশ, ইত্যাদি।\n\n"
    "0.11। আপনাকে খবর, বিশেষ অফার এবং অন্যান্য পণ্য, পরিষেবা এবং ইভেন্ট সম্পর্কে সাধারণ তথ্য প্রদান করতে যা আমরা অফার করি যা আপনার কাছে থাকা জিনিসগুলির মতো ইতিমধ্যেই কেনা বা জিজ্ঞাসা করা হয়েছে যদি না আপনি এই ধরনের তথ্য না পাওয়ার সিদ্ধান্ত নেন;\n\n"
    "0.12। আপনি যখন তথ্য প্রদান করেন তখন অন্য কোনো উপায়ে আমরা বর্ণনা করতে পারি;\n\n"
    "0.13। আপনার সম্মতিতে অন্য কোনো উদ্দেশ্যে।\n\n";

const String retention="Retention of Data\n\n";
const String retentionbn="ডেটা ধারণ করা";
const String retentionbrf="We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.\n\n"
    "We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.\n\n"
    "";
const String retentionbrfbn="এই গোপনীয়তা নীতিতে নির্ধারিত উদ্দেশ্যগুলির জন্য যতক্ষণ প্রয়োজন ততক্ষণ আমরা আপনার ব্যক্তিগত ডেটা সংরক্ষণ করব। আমরা আমাদের আইনি বাধ্যবাধকতাগুলি মেনে চলার জন্য প্রয়োজনীয় পরিমাণে আপনার ব্যক্তিগত ডেটা বজায় রাখব এবং ব্যবহার করব (উদাহরণস্বরূপ, প্রযোজ্য আইন মেনে চলার জন্য যদি আমাদের আপনার ডেটা বজায় রাখতে হয়), বিরোধগুলি সমাধান করতে এবং আমাদের আইনি চুক্তি এবং নীতিগুলি প্রয়োগ করতে হয়।\n\n"
    "আমরা অভ্যন্তরীণ বিশ্লেষণের উদ্দেশ্যে ব্যবহারের ডেটাও রাখব। ব্যবহারের ডেটা সাধারণত একটি সংক্ষিপ্ত সময়ের জন্য ধরে রাখা হয়, যখন এই ডেটা নিরাপত্তা জোরদার করতে বা আমাদের পরিষেবার কার্যকারিতা উন্নত করতে ব্যবহার করা হয়, অথবা আমরা এই ডেটা দীর্ঘ সময়ের জন্য ধরে রাখতে আইনিভাবে বাধ্য থাকি৷\n\n"
    "";

const String transfer="Transfer of Data";
const String transferbn="ডেটা স্থানান্তর";

const String transferbrf="Your information, including Personal Data, may be transferred to – and maintained on – computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.\n\n"
    "If you are located outside Bangladesh and choose to provide information to us, please note that we transfer the data, including Personal Data, to Bangladesh and process it there.\n\n"
    "Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.\n\n"
    "Jibika Intelligic Ltd. will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.\n\n"
    "";
const String transferbrfbn="আপনার তথ্য, ব্যক্তিগত ডেটা সহ, আপনার রাজ্য, প্রদেশ, দেশ বা অন্যান্য সরকারি এখতিয়ারের বাইরে অবস্থিত কম্পিউটারগুলিতে স্থানান্তরিত হতে পারে - এবং রক্ষণাবেক্ষণ করা যেতে পারে যেখানে ডেটা সুরক্ষা আইনগুলি আপনার এখতিয়ারের থেকে আলাদা হতে পারে৷\n\n"
    "আপনি যদি বাংলাদেশের বাইরে থাকেন এবং আমাদের তথ্য প্রদান করতে চান, তাহলে অনুগ্রহ করে মনে রাখবেন যে আমরা ব্যক্তিগত ডেটা সহ ডেটা বাংলাদেশে স্থানান্তর করি এবং সেখানে এটি প্রক্রিয়া করি।\n\n"
    "এই গোপনীয়তা নীতিতে আপনার সম্মতি এবং আপনার এই ধরনের তথ্য জমা দেওয়ার পরে সেই স্থানান্তরের জন্য আপনার চুক্তির প্রতিনিধিত্ব করে।\n\n"
    "জিবিকা ইন্টেলিজিক লিমিটেড আপনার ডেটা নিরাপদে এবং এই গোপনীয়তা নীতি অনুসারে ব্যবহার করা হয় তা নিশ্চিত করতে যুক্তিসঙ্গতভাবে প্রয়োজনীয় সমস্ত পদক্ষেপ নেবে এবং আপনার ব্যক্তিগত ডেটা কোনও সংস্থা বা কোনও দেশে স্থানান্তর করা হবে না যদি না সেখানে পর্যাপ্ত নিয়ন্ত্রণ না থাকে। আপনার ডেটা এবং অন্যান্য ব্যক্তিগত তথ্যের নিরাপত্তা।\n\n"
    "";

const String eight="Disclosure of Data";
const String eightbn="তথ্য প্রকাশ";
const String eightbrf="We may disclose personal information that we collect, or you provide:\n\n"
    "0.1. Disclosure for Law Enforcement.\n\n"
    "Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.\n\n"
    "0.2. Business Transaction.\n\n"
    "If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.\n\n"
    "0.3. Other cases. We may disclose your information also:\n\n"
    "0.3.1. to our subsidiaries and affiliates;\n\n"
    "0.3.2. to contractors, service providers, and other third parties we use to support our business;\n\n"
    "0.3.3. to fulfill the purpose for which you provide it;\n\n"
    "0.3.4. for the purpose of including your company’s logo on our website;\n\n"
    "0.3.5. for any other purpose disclosed by us when you provide the information;\n\n"
    "0.3.6. with your consent in any other cases;\n\n"
    "0.3.7. if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others.\n\n"
    "";
const String eightbrfbn="আমরা ব্যক্তিগত তথ্য প্রকাশ করতে পারি যা আমরা সংগ্রহ করি বা আপনি প্রদান করেন:\n\n"
    "0.1 আইন প্রয়োগকারীর জন্য প্রকাশ.\n\n"
    "কিছু নির্দিষ্ট পরিস্থিতিতে, আইন অনুসারে বা সরকারী কর্তৃপক্ষের বৈধ অনুরোধের প্রতিক্রিয়ায় আমাদের আপনার ব্যক্তিগত ডেটা প্রকাশ করতে হতে পারে।\n\n"
    "0.2। ব্যবসায়িক লেনদেনে.\n\n"
    "যদি আমরা বা আমাদের সহযোগী সংস্থাগুলি একত্রীকরণ, অধিগ্রহণ বা সম্পদ বিক্রয়ের সাথে জড়িত থাকে তবে আপনার ব্যক্তিগত ডেটা স্থানান্তরিত হতে পারে।\n\n"
    "0.3। অন্যান্য ক্ষেত্রে। আমরা আপনার তথ্যও প্রকাশ করতে পারি:\n\n"
    "0.3.1। আমাদের সহায়ক এবং সহযোগীদের কাছে;\n\n"
    "0.3.2। ঠিকাদার, পরিষেবা প্রদানকারী এবং অন্যান্য তৃতীয় পক্ষের কাছে যা আমরা আমাদের ব্যবসাকে সমর্থন করার জন্য ব্যবহার করি;\n\n"
    "0.3.3। আপনি যে উদ্দেশ্যে এটি প্রদান করেন তা পূরণ করতে;\n\n"
    "0.3.4। আমাদের ওয়েবসাইটে আপনার কোম্পানির লোগো অন্তর্ভুক্ত করার উদ্দেশ্যে;\n\n"
    "0.3.5। আপনি তথ্য প্রদান করার সময় আমাদের দ্বারা প্রকাশিত অন্য কোনো উদ্দেশ্যে;\n\n"
    "0.3.6। অন্য কোন ক্ষেত্রে আপনার সম্মতিতে;\n\n"
    "0.3.7। যদি আমরা বিশ্বাস করি যে কোম্পানি, আমাদের গ্রাহক বা অন্যদের অধিকার, সম্পত্তি বা নিরাপত্তা রক্ষার জন্য প্রকাশ প্রয়োজনীয় বা উপযুক্ত।\n\n"
    "";

const String nine="Security of Data";
const String ninebn="ডেটার নিরাপত্তা";
const String ninebrf="The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.\n\n"
    "";
const String ninebrfbn="আপনার ডেটার নিরাপত্তা আমাদের কাছে গুরুত্বপূর্ণ কিন্তু মনে রাখবেন যে ইন্টারনেটের মাধ্যমে সংক্রমণের কোনো পদ্ধতি বা ইলেকট্রনিক স্টোরেজের পদ্ধতি 100% নিরাপদ নয়। যদিও আমরা আপনার ব্যক্তিগত ডেটা সুরক্ষিত করার জন্য বাণিজ্যিকভাবে গ্রহণযোগ্য উপায়গুলি ব্যবহার করার চেষ্টা করি, আমরা এর সম্পূর্ণ নিরাপত্তার নিশ্চয়তা দিতে পারি না।\n\n"
    "";

const String ten="Your Data Protection Rights Under General Data Protection Regulation (GDPR)\n\n";
const String tenbn="জেনারেল ডেটা প্রোটেকশন রেগুলেশন (GDPR) এর অধীনে আপনার ডেটা সুরক্ষা অধিকার";
const String tenbrf="If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR.\n\n"
    "We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.\n\n"
    "If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at jibikaplexus@gmail.com.\n\n"
    "In certain circumstances, you have the following data protection rights:\n\n"
    "0.1. the right to access, update or to delete the information we have on you;\n\n"
    "0.2. the right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;\n\n"
    "0.3. the right to object. You have the right to object to our processing of your Personal Data;\n\n"
    "0.4. the right of restriction. You have the right to request that we restrict the processing of your personal information;\n\n"
    "0.5. the right to data portability. You have the right to be provided with a copy of your Personal Data in a structured, machine-readable and commonly used format;\n\n"
    "0.6. the right to withdraw consent. You also have the right to withdraw your consent at any time where we rely on your consent to process your personal information;\n\n"
    "Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not able to provide Service without some necessary data.\n\n"
    "You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).\n\n"
    "";
const String tenbrfbn="আপনি যদি ইউরোপীয় ইউনিয়ন (EU) এবং ইউরোপীয় অর্থনৈতিক অঞ্চল (EEA) এর বাসিন্দা হন তবে আপনার কিছু ডেটা সুরক্ষা অধিকার রয়েছে, যা GDPR এর আওতায় রয়েছে।\n\n"
    "আমরা আপনাকে আপনার ব্যক্তিগত ডেটার ব্যবহার সংশোধন, সংশোধন, মুছে বা সীমিত করার অনুমতি দেওয়ার জন্য যুক্তিসঙ্গত পদক্ষেপ নেওয়ার লক্ষ্য রাখি।\n\n"
    "আপনি যদি জানাতে চান যে আমরা আপনার সম্পর্কে কী ব্যক্তিগত ডেটা রাখি এবং আপনি যদি এটি আমাদের সিস্টেম থেকে সরিয়ে দিতে চান, তাহলে অনুগ্রহ করে আমাদের ইমেল করুন \n\n"
    "নির্দিষ্ট পরিস্থিতিতে, আপনার নিম্নলিখিত ডেটা সুরক্ষা অধিকার রয়েছে:\n\n"
    "0.1 আমাদের আপনার কাছে থাকা তথ্য অ্যাক্সেস, আপডেট বা মুছে ফেলার অধিকার;\n\n"
    "0.2। সংশোধনের অধিকার। আপনার তথ্য সংশোধন করার অধিকার আছে যদি সেই তথ্যটি ভুল বা অসম্পূর্ণ হয়;\n\n"
    "0.3। আপত্তি করার অধিকার। আপনার ব্যক্তিগত ডেটা আমাদের প্রক্রিয়াকরণে আপত্তি করার অধিকার আপনার আছে;\n\n"
    "0.4 সীমাবদ্ধতার অধিকার। আপনার কাছে অনুরোধ করার অধিকার আছে যে আমরা আপনার ব্যক্তিগত তথ্যের প্রক্রিয়াকরণ সীমাবদ্ধ করি;\n\n"
    "0.5। ডেটা বহনযোগ্যতার অধিকার। একটি কাঠামোগত, মেশিন-পাঠযোগ্য এবং সাধারণত ব্যবহৃত বিন্যাসে আপনার ব্যক্তিগত ডেটার একটি অনুলিপি প্রদান করার অধিকার আপনার আছে;\n\n"
    "0.6। সম্মতি প্রত্যাহার করার অধিকার। যে কোনো সময়ে আপনার সম্মতি প্রত্যাহার করার অধিকার আছে যেখানে আমরা আপনার ব্যক্তিগত তথ্য প্রক্রিয়া করার জন্য আপনার সম্মতির উপর নির্ভর করি;\n\n"
    "অনুগ্রহ করে মনে রাখবেন যে এই ধরনের অনুরোধে সাড়া দেওয়ার আগে আমরা আপনাকে আপনার পরিচয় যাচাই করতে বলতে পারি। দয়া করে মনে রাখবেন, আমরা কিছু প্রয়োজনীয় ডেটা ছাড়া পরিষেবা প্রদান করতে সক্ষম নাও হতে পারি।\n\n"
    "আপনার ব্যক্তিগত ডেটা আমাদের সংগ্রহ এবং ব্যবহার সম্পর্কে ডেটা সুরক্ষা কর্তৃপক্ষের কাছে অভিযোগ করার অধিকার আপনার আছে। আরও তথ্যের জন্য, অনুগ্রহ করে ইউরোপীয় অর্থনৈতিক অঞ্চলে (EEA) আপনার স্থানীয় ডেটা সুরক্ষা কর্তৃপক্ষের সাথে যোগাযোগ করুন।\n\n"
    "";

const String eleven="Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)\n\n";
const String elevenbn="ক্যালিফোর্নিয়া প্রাইভেসি প্রোটেকশন অ্যাক্ট (CalOPPA) এর অধীনে আপনার ডেটা সুরক্ষা অধিকার\n\n";
const String elevenbrf="CalOPPA is the first state law in the nation to require commercial websites and online services to post a privacy policy. The law’s reach stretches well beyond California to require a person or company in the United States (and conceivable the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy.\n\n"
    "According to CalOPPA we agree to the following:\n\n"
    "0.1. users can visit our site anonymously;\n\n"
    "0.2. our Privacy Policy link includes the word “Privacy”, and can easily be found on the home page of our website;\n\n"
    "0.3. users will be notified of any privacy policy changes on our Privacy Policy Page;\n\n"
    "0.4. users are able to change their personal information by emailing us at jibikaplexus@gmail.com.\n\n"
    "Our Policy on “Do Not Track” Signals:\n\n"
    "We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.\n\n"
    "You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.\n\n"
    "";
const String elevenbrfbn="CalOPPA হল দেশের প্রথম রাষ্ট্রীয় আইন যেখানে একটি গোপনীয়তা নীতি পোস্ট করার জন্য বাণিজ্যিক ওয়েবসাইট এবং অনলাইন পরিষেবাগুলির প্রয়োজন হয়৷ আইনের নাগাল ক্যালিফোর্নিয়ার বাইরেও প্রসারিত হয়েছে মার্কিন যুক্তরাষ্ট্রে (এবং ধারণাযোগ্য) এমন একজন ব্যক্তি বা সংস্থার প্রয়োজন যা ক্যালিফোর্নিয়ার গ্রাহকদের কাছ থেকে ব্যক্তিগতভাবে শনাক্তকরণযোগ্য তথ্য সংগ্রহ করে এমন ওয়েবসাইট পরিচালনা করে যাতে তার ওয়েবসাইটে একটি সুস্পষ্ট গোপনীয়তা নীতি পোস্ট করা হয় যাতে সঠিক তথ্য সংগ্রহ করা হচ্ছে এবং সেগুলি ব্যক্তি যাদের সাথে এটি ভাগ করা হচ্ছে, এবং এই নীতি মেনে চলা।\n\n"
    "CalOPPA অনুযায়ী আমরা নিম্নলিখিতগুলির সাথে সম্মত:\n\n"
    "0.1 ব্যবহারকারীরা বেনামে আমাদের সাইট পরিদর্শন করতে পারেন;\n\n"
    "0.2। আমাদের গোপনীয়তা নীতির লিঙ্কে 'গোপনীয়তা' শব্দটি অন্তর্ভুক্ত রয়েছে এবং আমাদের ওয়েবসাইটের হোম পেজে সহজেই পাওয়া যাবে;\n\n"
    "0.3। ব্যবহারকারীদের আমাদের গোপনীয়তা নীতি পৃষ্ঠায় গোপনীয়তা নীতি পরিবর্তনের বিষয়ে অবহিত করা হবে;\n\n"
    "0.4 ব্যবহারকারীরা আমাদেরকে jibikaplexus@gmail.com এ ইমেল করে তাদের ব্যক্তিগত তথ্য পরিবর্তন করতে পারবেন।\n\n"
    "আমাদের নীতি 'ট্র্যাক করবেন না' সংকেত:\n\n"
    "আমরা ডু নট ট্র্যাক সিগন্যালকে সম্মান করি এবং যখন ডু নট ট্র্যাক ব্রাউজার মেকানিজম থাকে তখন ট্র্যাক করি না, কুকিজ লাগাই না বা বিজ্ঞাপন ব্যবহার করি না। ট্র্যাক করবেন না এমন একটি পছন্দ যা আপনি আপনার ওয়েব ব্রাউজারে সেট করতে পারেন এমন ওয়েবসাইটগুলিকে জানানোর জন্য যেগুলি আপনি ট্র্যাক করতে চান না৷\n\n"
    "আপনি আপনার ওয়েব ব্রাউজারের পছন্দ বা সেটিংস পৃষ্ঠায় গিয়ে ডু নট ট্র্যাক সক্ষম বা নিষ্ক্রিয় করতে পারেন।\n\n";

const String tweleve="Your Data Protection Rights under the California Consumer Privacy Act (CCPA)\n\n";
const String twelvebn="ক্যালিফোর্নিয়া কনজিউমার প্রাইভেসি অ্যাক্ট (CCPA) এর অধীনে আপনার ডেটা সুরক্ষা অধিকার";
const String twelvebrf="If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us\n\n"
    "0.1. What personal information we have about you. If you make this request, we will return to you:\n\n"
    "0.0.1. The categories of personal information we have collected about you.\n\n"
    "0.0.2. The categories of sources from which we collect your personal information.\n\n"
    "0.0.3. The business or commercial purpose for collecting or selling your personal information.\n\n"
    "0.0.4. The categories of third parties with whom we share personal information.\n\n"
    "0.0.5. The specific pieces of personal information we have collected about you.\n\n"
    "0.0.6. A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have not sold your personal information, we will inform you of that fact.\n\n"
    "0.0.7. A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.\n\n"
    "Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.\n\n"
    "0.2. To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request from our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.\n\n"
    "0.3. To stop selling your personal information. We don’t sell or rent your personal information to any third parties for any purpose. We do not sell your personal information for monetary consideration. However, under some circumstances, a transfer of personal information to a third party, or within our family of companies, without monetary consideration may be considered a “sale” under California law. You are the only owner of your Personal Data and can request disclosure or deletion at any time.\n\n"
    "If you submit a request to stop selling your personal information, we will stop making such transfers.\n\n"
    "Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in certain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.\n\n"
    "To exercise your California data protection rights described above, please send your request(s) by email: jibikaplexus@gmail.com.\n\n"
    "Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.\n\n"
    "";
const String twelvebrfbn="আপনি যদি একজন ক্যালিফোর্নিয়ার বাসিন্দা হন, তাহলে আমরা আপনার সম্পর্কে কী ডেটা সংগ্রহ করি তা শিখতে, আপনার ডেটা মুছে দিতে বলুন এবং এটি বিক্রি (ভাগ) না করার জন্য আপনার অধিকার রয়েছে৷ আপনার ডেটা সুরক্ষা অধিকার প্রয়োগ করতে, আপনি কিছু অনুরোধ করতে পারেন এবং আমাদের জিজ্ঞাসা করতে পারেন:\n\n"
    "0.1 আমরা আপনার সম্পর্কে কি ব্যক্তিগত তথ্য আছে. আপনি যদি এই অনুরোধ করেন, আমরা আপনার কাছে ফিরে আসব:\n\n"
    "0.0.1 ব্যক্তিগত তথ্যের বিভাগগুলি আমরা আপনার সম্পর্কে সংগ্রহ করেছি।\n\n"
    "0.0.2। উৎসের বিভাগগুলি যেখান থেকে আমরা আপনার ব্যক্তিগত তথ্য সংগ্রহ করি।\n\n"
    "0.0.3। আপনার ব্যক্তিগত তথ্য সংগ্রহ বা বিক্রি করার জন্য ব্যবসা বা বাণিজ্যিক উদ্দেশ্য।\n\n"
    "0.0.4 তৃতীয় পক্ষের বিভাগ যাদের সাথে আমরা ব্যক্তিগত তথ্য শেয়ার করি।\n\n"
    "0.0.5। আমরা আপনার সম্পর্কে সংগ্রহ করেছি ব্যক্তিগত তথ্য নির্দিষ্ট টুকরা.\n\n"
    "0.0.6। ব্যক্তিগত তথ্যের শ্রেণীবিভাগের একটি তালিকা যা আমরা বিক্রি করেছি, অন্য কোনো কোম্পানির ক্যাটাগরি সহ আমরা এটি বিক্রি করেছি। আমরা যদি আপনার ব্যক্তিগত তথ্য বিক্রি না করে থাকি, তাহলে আমরা আপনাকে সেই সত্যটি জানাব।\n\n"
    "0.0.7 ব্যক্তিগত তথ্যের বিভাগগুলির একটি তালিকা যা আমরা একটি ব্যবসায়িক উদ্দেশ্যে প্রকাশ করেছি, অন্য যেকোন কোম্পানির সাথে আমরা এটি শেয়ার করেছি।\n\n"
    "অনুগ্রহ করে মনে রাখবেন, আপনি আমাদেরকে এই তথ্য সরবরাহ করার জন্য বারো মাসের মধ্যে দুই বার পর্যন্ত বলার অধিকারী। আপনি যখন এই অনুরোধ করেন, প্রদত্ত তথ্য সীমাবদ্ধ হতে পারে যে ব্যক্তিগত তথ্য আমরা গত 12 মাসে আপনার সম্পর্কে সংগ্রহ করেছি।\n\n"
    "0.2। আপনার ব্যক্তিগত তথ্য মুছে ফেলার জন্য. আপনি যদি এই অনুরোধ করেন, আমরা আমাদের রেকর্ড থেকে আপনার অনুরোধের তারিখ হিসাবে আপনার সম্পর্কে আমাদের কাছে থাকা ব্যক্তিগত তথ্য মুছে ফেলব এবং যেকোনো পরিষেবা প্রদানকারীকে একই কাজ করার নির্দেশ দিব। কিছু ক্ষেত্রে, তথ্য ডি-শনাক্তকরণের মাধ্যমে মুছে ফেলা হতে পারে। আপনি যদি আপনার ব্যক্তিগত তথ্য মুছে ফেলার সিদ্ধান্ত নেন, আপনি হয়ত কিছু ফাংশন ব্যবহার করতে পারবেন না যার জন্য আপনার ব্যক্তিগত তথ্যের প্রয়োজন হয়।\n\n"
    "0.3। আপনার ব্যক্তিগত তথ্য বিক্রি বন্ধ করতে. আমরা কোনো উদ্দেশ্যে কোনো তৃতীয় পক্ষের কাছে আপনার ব্যক্তিগত তথ্য বিক্রি বা ভাড়া দেই না। আমরা আর্থিক বিবেচনার জন্য আপনার ব্যক্তিগত তথ্য বিক্রি করি না। যাইহোক, কিছু পরিস্থিতিতে, আর্থিক বিবেচনা ছাড়াই তৃতীয় পক্ষের কাছে বা আমাদের কোম্পানির পরিবারের মধ্যে ব্যক্তিগত তথ্যের স্থানান্তর ক্যালিফোর্নিয়ার আইনের অধীনে একটি 'বিক্রয়' হিসাবে বিবেচিত হতে পারে। আপনি আপনার ব্যক্তিগত ডেটার একমাত্র মালিক এবং যেকোনো সময় প্রকাশ বা মুছে ফেলার অনুরোধ করতে পারেন।\n\n"
    "আপনি যদি আপনার ব্যক্তিগত তথ্য বিক্রি বন্ধ করার জন্য একটি অনুরোধ জমা দেন, আমরা এই ধরনের স্থানান্তর করা বন্ধ করে দেব।\n\n"
    "অনুগ্রহ করে মনে রাখবেন, আপনি যদি আমাদেরকে আপনার ডেটা মুছে ফেলতে বা বিক্রি করা বন্ধ করতে বলেন, তাহলে এটি আমাদের সাথে আপনার অভিজ্ঞতাকে প্রভাবিত করতে পারে এবং আপনি কিছু নির্দিষ্ট প্রোগ্রাম বা সদস্যপদ পরিষেবায় অংশগ্রহণ করতে পারবেন না যার জন্য আপনার ব্যক্তিগত তথ্য ব্যবহার করার প্রয়োজন হয়। কিন্তু কোনো অবস্থাতেই, আমরা আপনার অধিকার প্রয়োগের জন্য আপনার প্রতি বৈষম্য করব না।\n\n"
    "উপরে বর্ণিত আপনার ক্যালিফোর্নিয়া ডেটা সুরক্ষা অধিকার ব্যবহার করতে, অনুগ্রহ করে আপনার অনুরোধ(গুলি) ইমেলের মাধ্যমে পাঠান: jibikaplexus@gmail.com।\n\n"
    "ক্যালিফোর্নিয়া কনজিউমার প্রাইভেসি অ্যাক্টের সংক্ষিপ্ত বিবরণ, উপরে বর্ণিত আপনার ডেটা সুরক্ষা অধিকারগুলি CCPA-এর আওতায় রয়েছে। আরও জানতে, অফিসিয়াল ক্যালিফোর্নিয়া আইনী তথ্য ওয়েবসাইট দেখুন। CCPA 01/01/2020 থেকে কার্যকর হয়েছে।\n\n"
    "";
const String thirteen="Service Providers\n\n";
const String thirteenbn="পরিষেবা প্রদানকারী\n\n";
const String thirteenbrf = "We may employ third party companies and individuals to facilitate our Service (“Service Providers”), provide Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.\n"
    "These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.\n\n";
const String thirteenbrfbn="আমরা আমাদের পরিষেবা ('পরিষেবা প্রদানকারী'), আমাদের পক্ষ থেকে পরিষেবা প্রদান করতে, পরিষেবা-সম্পর্কিত পরিষেবাগুলি সম্পাদন করতে বা আমাদের পরিষেবা কীভাবে ব্যবহার করা হয় তা বিশ্লেষণে আমাদের সহায়তা করার জন্য তৃতীয় পক্ষের কোম্পানি এবং ব্যক্তিদের নিয়োগ করতে পারি।\n\n"
    "এই তৃতীয় পক্ষের আপনার ব্যক্তিগত ডেটাতে অ্যাক্সেস রয়েছে শুধুমাত্র আমাদের পক্ষে এই কাজগুলি সম্পাদন করার জন্য এবং অন্য কোন উদ্দেশ্যে এটি প্রকাশ বা ব্যবহার না করার জন্য বাধ্য।\n\n"
    "";

const String fourteen="Analytics";
const String fourteenbn="বিশ্লেষণ";
const String fourteenbrf="We may use third-party Service Providers to monitor and analyze the use of our Service.\n\n";
const String fourteenbrfbn="আমরা আমাদের পরিষেবার ব্যবহার নিরীক্ষণ এবং বিশ্লেষণ করতে তৃতীয় পক্ষের পরিষেবা প্রদানকারীদের ব্যবহার করতে পারি।\n\n";


const String fifteen="CI/CD tools\n\n";
const String fifteenbn="CI/CD টুলস\n\n";
const String fifteenbrf="We may use third-party Service Providers to automate the development process of our Service.\n\n";
const String fifteenbrfbn="আমরা আমাদের পরিষেবার উন্নয়ন প্রক্রিয়া স্বয়ংক্রিয় করতে তৃতীয় পক্ষের পরিষেবা প্রদানকারীদের ব্যবহার করতে পারি।\n\n";

const String sixteen="Behavioral Remarketing\n\n";
const String sixteenbn="আচরণগত পুনঃবিপণন\n\n";
const String sixteenbrf="We may use remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your past visits to our Service.\n\n";
const String sixteenbrfbn="আপনি আমাদের পরিষেবা পরিদর্শন করার পরে আমরা আপনাকে তৃতীয় পক্ষের ওয়েবসাইটগুলিতে বিজ্ঞাপন দেওয়ার জন্য পুনরায় বিপণন পরিষেবাগুলি ব্যবহার করতে পারি। আমরা এবং আমাদের তৃতীয় পক্ষের বিক্রেতারা আমাদের পরিষেবাতে আপনার অতীত পরিদর্শনের উপর ভিত্তি করে বিজ্ঞাপন, অপ্টিমাইজ এবং পরিবেশন করতে কুকি ব্যবহার করি।\n\n";

const String seventeen="Payments";
const String seventeenbn="পেমেন্ট";
const String seventeenbrf="We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).\n\n"
    "We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.\n\n"
    "";
const String seventeenbrfbn="আমরা পরিষেবার মধ্যে অর্থ প্রদানের পণ্য এবং/অথবা পরিষেবা প্রদান করতে পারি। সেই ক্ষেত্রে, আমরা অর্থপ্রদান প্রক্রিয়াকরণের জন্য তৃতীয় পক্ষের পরিষেবাগুলি ব্যবহার করি (যেমন পেমেন্ট প্রসেসর)।\n\n"
    "আমরা আপনার পেমেন্ট কার্ডের বিশদ সংরক্ষণ বা সংগ্রহ করব না। এই তথ্যটি সরাসরি আমাদের তৃতীয় পক্ষের পেমেন্ট প্রসেসরদের প্রদান করা হয় যাদের আপনার ব্যক্তিগত তথ্যের ব্যবহার তাদের গোপনীয়তা নীতি দ্বারা পরিচালিত হয়। এই পেমেন্ট প্রসেসরগুলি পিসিআই সিকিউরিটি স্ট্যান্ডার্ড কাউন্সিল দ্বারা পরিচালিত PCI-DSS দ্বারা নির্ধারিত মানগুলি মেনে চলে, যা ভিসা, মাস্টারকার্ড, আমেরিকান এক্সপ্রেস এবং ডিসকভারের মতো ব্র্যান্ডগুলির যৌথ প্রচেষ্টা। PCI-DSS প্রয়োজনীয়তাগুলি অর্থপ্রদানের তথ্যের নিরাপদ হ্যান্ডলিং নিশ্চিত করতে সহায়তা করে।\n\n"
    "";

const String eightteen="Links to Other Sites\n\n";
const String eightteenbn="অন্যান্য সাইটের লিঙ্ক\n\n";
const String eightteenbrf="Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.\n\n"
    "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.\n\n"
    "";
const String eightteenbrfbn="আমাদের পরিষেবাতে আমাদের দ্বারা পরিচালিত নয় এমন অন্যান্য সাইটের লিঙ্ক থাকতে পারে। আপনি যদি তৃতীয় পক্ষের লিঙ্কে ক্লিক করেন তবে আপনাকে সেই তৃতীয় পক্ষের সাইটে নির্দেশিত করা হবে। আমরা দৃঢ়ভাবে আপনি পরিদর্শন প্রতিটি সাইটের গোপনীয়তা নীতি পর্যালোচনা করার পরামর্শ.\n\n"
    "আমাদের কোনো নিয়ন্ত্রণ নেই এবং কোনো তৃতীয় পক্ষের সাইট বা পরিষেবার বিষয়বস্তু, গোপনীয়তা নীতি বা অনুশীলনের জন্য কোনো দায়বদ্ধতা নেই।\n\n"
    "";

const String nineteen="Children’s Privacy\n\n";
const String nineteenbn="শিশুদের গোপনীয়তা\n\n";
const String nineteenbrf="Our Services are not intended for use by children under the age of 18 (“Child” or “Children”).\n\n"
    "We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.\n\n"
    "";
const String nineteenbrfbn="আমাদের পরিষেবাগুলি 18 বছরের কম বয়সী শিশুদের দ্বারা ব্যবহারের উদ্দেশ্যে নয় ('শিশু' বা 'শিশু')৷\n\n"
    "আমরা জেনেশুনে 18 বছরের কম বয়সী শিশুদের কাছ থেকে ব্যক্তিগতভাবে শনাক্তযোগ্য তথ্য সংগ্রহ করি না৷ আপনি যদি সচেতন হন যে একটি শিশু আমাদের ব্যক্তিগত ডেটা সরবরাহ করেছে, অনুগ্রহ করে আমাদের সাথে যোগাযোগ করুন৷ আমরা যদি সচেতন হই যে আমরা পিতামাতার সম্মতি যাচাই ছাড়াই শিশুদের কাছ থেকে ব্যক্তিগত ডেটা সংগ্রহ করেছি, আমরা আমাদের সার্ভারগুলি থেকে সেই তথ্যগুলি সরানোর জন্য পদক্ষেপ নিই৷\n\n"
    "";

const String tweenty="Changes to This Privacy Policy\n\n";
const String tweentybn="এই গোপনীয়তা নীতিতে পরিবর্তন\n\n";
const String tweentybrf="We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.\n\n"
    "We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.\n\n"
    "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.\v\v"
    "";
const String tweentybrfbn="আমরা সময়ে সময়ে আমাদের গোপনীয়তা নীতি আপডেট করতে পারি। আমরা এই পৃষ্ঠায় নতুন গোপনীয়তা নীতি পোস্ট করে কোনো পরিবর্তন সম্পর্কে আপনাকে অবহিত করব।\n\n"
    "পরিবর্তনটি কার্যকর হওয়ার আগে আমরা আপনাকে ইমেল এবং/অথবা আমাদের পরিষেবাতে একটি বিশিষ্ট বিজ্ঞপ্তির মাধ্যমে জানাব এবং এই গোপনীয়তা নীতির শীর্ষে 'কার্যকর তারিখ' আপডেট করব৷\n\n"
    "যেকোনো পরিবর্তনের জন্য আপনাকে পর্যায়ক্রমে এই গোপনীয়তা নীতি পর্যালোচনা করার পরামর্শ দেওয়া হচ্ছে। এই গোপনীয়তা নীতিতে পরিবর্তনগুলি কার্যকর হয় যখন সেগুলি এই পৃষ্ঠায় পোস্ট করা হয়৷\n\n"
    "";

const twentyone="Contact Us\n\n";
const twentyonebn="আমাদের সাথে যোগাযোগ করুন\n\n";
const twentyonebrf="If you have any questions about this Privacy Policy, please contact us by email: jibikaplexus@gmail.com.\n\n";
const twentyonebrfbn="এই গোপনীয়তা নীতি সম্পর্কে আপনার কোন প্রশ্ন থাকলে, অনুগ্রহ করে ইমেলের মাধ্যমে আমাদের সাথে যোগাযোগ করুন: jibikaplexus@gmail.com।\n\n";